// このファイルは自動生成によって上書きされます。

import React from 'react'
import { RouteObject } from 'react-router-dom'
import { SideMenuItem } from './autogenerated-menu'

/** 自動生成されたあとのソースコードに対してカスタマイズを加えられる箇所の一覧とその設定 */
export type AutoGeneratedCustomizer = {
  /** Raect router のルーティング処理（クライアント側のURLとページの紐づき設定）を編集するReactフック */
  useRouteCustomizer?: () => ((defaultRoutes: RouteObject[]) => RouteObject[])
  /** サイドメニューをカスタマイズするReactフック */
  useSideMenuCustomizer?: () => ((defaultMenu: SideMenu) => SideMenu)
  /** ログイン画面を使用する場合はここに指定してください。ログイン成功の場合は引数のコンポーネントをそのまま返してください。 */
  LoginPage?: (props: {
    /** ログイン済みの場合に表示されるコンポーネント */
    LoggedInContents: JSX.Element
  }) => React.ReactNode
}

/** サイドメニューの型 */
type SideMenu = {
  /** サイドメニュー（上半分） */
  top: SideMenuItem[]
  /** サイドメニュー（下半分） */
  bottom: SideMenuItem[]
}

export const createEmptyCustomizerContext = (): AutoGeneratedCustomizer => ({
})

const CustomizerContext = React.createContext<AutoGeneratedCustomizer>(createEmptyCustomizerContext())
export const CustomizerContextProvider = CustomizerContext.Provider
export const useCustomizerContext = () => React.useContext(CustomizerContext)
