/** 自動生成されたあとのソースコードに対してカスタマイズを加えられる箇所の一覧とその設定 */
export type AutoGeneratedCustomizer = {
  /** Raect router のルーティング処理（クライアント側のURLとページの紐づき設定）を編集します。 */
  modifyRoutes?: (defaultRoutes: { url: string, el: JSX.Element }[]) => ({ url: string, el: JSX.Element })[]
}
