import React from "react"
import * as Icon from "@heroicons/react/24/solid"
import { useToggle2 } from "../../__autoGenerated/util"
import * as Input from "../../__autoGenerated/input"

/** アコーディオン */
export const Accordion = (props: {
  title?: React.ReactNode
  children?: React.ReactNode
  defaultOpen?: boolean
  className?: string
}) => {
  const { opened, toggle } = useToggle2(props.defaultOpen)

  return (
    <div className="flex flex-col gap-1">
      <div onClick={toggle} className="flex flex-wrap justify-start items-center gap-1 cursor-pointer">
        <Input.IconButton icon={opened ? Icon.ChevronDownIcon : Icon.ChevronRightIcon} hideText>折りたたみ</Input.IconButton>
        {props.title}
      </div>
      <div className={`flex-1 ${props.className ?? ''} ${opened ? '' : 'hidden'}`}>
        {props.children}
      </div>
    </div>
  )
}
