using System;
using System.Collections.Generic;
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Parsing;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Nijo.Core;
using Nijo.Util.DotnetEx;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;

[assembly: InternalsVisibleTo("Nijo.IntegrationTest")]

namespace Nijo {
    public class Program {

        static async Task<int> Main(string[] args) {
            var logger = ILoggerExtension.CreateConsoleLogger();
            var cancellationTokenSource = new CancellationTokenSource();
            Console.CancelKeyPress += (sender, e) => {
                cancellationTokenSource.Cancel();

                // キャンセル時のリソース解放を適切に行うために既定の動作（アプリケーション終了）を殺す
                e.Cancel = true;
            };

            var rootCommand = DefineCommand(logger, cancellationTokenSource);

            var parser = new CommandLineBuilder(rootCommand)
                .UseDefaults()

                // 例外処理
                .UseExceptionHandler((ex, _) => {
                    if (ex is OperationCanceledException) {
                        Console.Error.WriteLine("キャンセルされました。");
                    } else {
                        cancellationTokenSource.Cancel();
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.Error.WriteLine(ex.ToString());
                        Console.ResetColor();
                    }
                })
                .Build();

            return await parser.InvokeAsync(args);
        }

        private static RootCommand DefineCommand(ILogger logger, CancellationTokenSource cancellationTokenSource) {
            var rootCommand = new RootCommand("nijo");

            var services = new ServiceCollection();
            GeneratedProject.ConfigureDefaultServices(services);
            var serviceProvider = services.BuildServiceProvider();

            // 引数定義
            var path = new Argument<string?>(() => null);
            var applicationName = new Argument<string?>();
            var keepTempIferror = new Option<bool>("--keep-temp-if-error", description: "エラー発生時、原因調査ができるようにするため一時フォルダを削除せず残します。");

            // コマンド定義
            var create = new Command(name: "create", description: "新しいプロジェクトを作成します。") { applicationName, keepTempIferror };
            create.SetHandler((applicationName, keepTempIferror) => {
                if (!CheckIfToolIsAvailable(cancellationTokenSource.Token, "dotnet", "npm", "git")) return;
                if (string.IsNullOrEmpty(applicationName)) throw new ArgumentException($"Application name is required.");
                var projectRootDir = Path.Combine(Directory.GetCurrentDirectory(), applicationName);
                GeneratedProject.Create(
                    projectRootDir,
                    applicationName,
                    keepTempIferror,
                    serviceProvider,
                    cancellationTokenSource.Token,
                    logger);
            }, applicationName, keepTempIferror);
            rootCommand.AddCommand(create);

            var debug = new Command(name: "debug", description: "プロジェクトのデバッグを開始します。") { path };
            debug.SetHandler(async (path) => {
                if (!CheckIfToolIsAvailable(cancellationTokenSource.Token, "dotnet", "npm")) return;
                var project = GeneratedProject.Open(path, serviceProvider, logger);
                await project.Debugger.StartDebugging(cancellationTokenSource.Token);
            }, path);
            rootCommand.AddCommand(debug);

            var fix = new Command(name: "fix", description: "コード自動生成処理をかけなおします。") { path };
            fix.SetHandler((path) => {
                GeneratedProject
                    .Open(path, serviceProvider, logger)
                    .CodeGenerator
                    .UpdateAutoGeneratedCode();
            }, path);
            rootCommand.AddCommand(fix);

            var dump = new Command(name: "dump", description: "スキーマ定義から構築したスキーマ詳細をTSV形式で出力します。") { path };
            dump.SetHandler((path) => {
                var tsv = GeneratedProject
                    .Open(path, serviceProvider, logger)
                    .BuildSchema()
                    .DumpTsv();
                Console.WriteLine(tsv);
            }, path);
            rootCommand.AddCommand(dump);

            return rootCommand;
        }


        /// <summary>
        /// 外部ツールが使用可能かどうかを検査する（'--version' コマンドを実行することで確認）
        /// </summary>
        private static bool CheckIfToolIsAvailable(CancellationToken cancellationToken, params string[] names) {
            var ok = true;
            foreach (var name in names) {
                try {
                    var terminal = new Terminal(".", ILoggerExtension.CreateConsoleLogger());
                    terminal.Run(new[] { name, "--version" }, cancellationToken).Wait();
                } catch (OperationCanceledException) {
                    throw;
                } catch {
                    Console.Error.WriteLine($"Command line tool '{name}' is not available. Please install it from the official website of '{name}'.");
                    ok = false;
                }
            }
            return ok;
        }
    }
}
