using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;

namespace Nijo.WebService.DemoMode;

/// <summary>
/// AIチャットの実行前後で、ワークスペース内のソースが実際に変更されたかを判定するためのスナップショット。
/// スキーマ(nijo.xml)と手書きコードの両方を対象とする。エージェントはビルドを実行できないため、
/// ここで検知した変更をもとにサーバー側が自動ビルド・デモアプリ再起動を行う。
/// </summary>
public sealed class WorkspaceSourceSnapshot {

    /// <summary>
    /// スナップショットの対象とするワークスペース直下のフォルダ。
    /// エージェントが編集しうる、かつデモアプリのビルド結果に影響するものだけを対象とする。
    /// (Core.AutoGenerated 等の自動生成コードはサーバー側の再生成でしか変わらないため対象外)
    /// </summary>
    private static readonly string[] TARGET_DIRECTORIES = ["Core", "WebApi", "client"];

    /// <summary>
    /// 対象フォルダ配下でも無視するフォルダ名。
    /// 自動生成コード・ビルド成果物・依存パッケージなど、エージェントの編集以外の要因で
    /// 変化するもの(これらを含めると変更を誤検知して無駄なリビルドが走る)。
    /// </summary>
    private static readonly HashSet<string> IGNORED_DIRECTORY_NAMES = new(StringComparer.OrdinalIgnoreCase) {
        "__AutoGenerated", "bin", "obj", "node_modules", "dist", "wwwroot",
    };

    /// <summary>ワークスペースルートからの相対パス → ファイル内容のハッシュ</summary>
    private readonly IReadOnlyDictionary<string, string> _fileHashes;

    private WorkspaceSourceSnapshot(IReadOnlyDictionary<string, string> fileHashes) {
        _fileHashes = fileHashes;
    }

    public static WorkspaceSourceSnapshot Capture(string workspaceRoot) {
        var fileHashes = new Dictionary<string, string>();

        var schemaPath = Path.Combine(workspaceRoot, "nijo.xml");
        if (File.Exists(schemaPath)) {
            fileHashes[SCHEMA_XML] = ComputeFileHash(schemaPath);
        }
        foreach (var directory in TARGET_DIRECTORIES) {
            var absoluteDirectory = Path.Combine(workspaceRoot, directory);
            if (!Directory.Exists(absoluteDirectory)) continue;
            CollectFileHashes(absoluteDirectory, workspaceRoot, fileHashes);
        }
        return new WorkspaceSourceSnapshot(fileHashes);
    }

    /// <summary>
    /// このスナップショットと過去のスナップショットを比較し、追加・削除・内容変更されたファイルを列挙する。
    /// </summary>
    public WorkspaceSourceChanges DiffFrom(WorkspaceSourceSnapshot before) {
        var changedPaths = _fileHashes.Keys.Union(before._fileHashes.Keys)
            .Where(path => _fileHashes.GetValueOrDefault(path) != before._fileHashes.GetValueOrDefault(path))
            .OrderBy(path => path, StringComparer.Ordinal)
            .ToList();
        return new WorkspaceSourceChanges(changedPaths);
    }

    internal const string SCHEMA_XML = "nijo.xml";

    private static void CollectFileHashes(string directory, string workspaceRoot, Dictionary<string, string> fileHashes) {
        foreach (var file in Directory.EnumerateFiles(directory)) {
            fileHashes[Path.GetRelativePath(workspaceRoot, file)] = ComputeFileHash(file);
        }
        foreach (var subDirectory in Directory.EnumerateDirectories(directory)) {
            if (IGNORED_DIRECTORY_NAMES.Contains(Path.GetFileName(subDirectory))) continue;
            CollectFileHashes(subDirectory, workspaceRoot, fileHashes);
        }
    }

    private static string ComputeFileHash(string path) {
        try {
            using var stream = File.OpenRead(path);
            return Convert.ToHexString(SHA256.HashData(stream));
        } catch (IOException) {
            // 読み取れないファイルはサイズ+更新日時で代用する(編集されれば更新日時が変わり、変更として検知できる)
            var info = new FileInfo(path);
            return $"unreadable:{info.Length}:{info.LastWriteTimeUtc.Ticks}";
        }
    }
}

/// <summary>
/// <see cref="WorkspaceSourceSnapshot.DiffFrom"/> の結果。AIチャットによって変更されたファイルの一覧。
/// </summary>
public sealed class WorkspaceSourceChanges {

    public WorkspaceSourceChanges(IReadOnlyList<string> changedPaths) {
        ChangedPaths = changedPaths;
    }

    /// <summary>追加・削除・内容変更されたファイルのワークスペースルートからの相対パス</summary>
    public IReadOnlyList<string> ChangedPaths { get; }

    public bool Any => ChangedPaths.Count > 0;

    /// <summary>
    /// デモアプリのDBファイルを作り直す必要がある変更を含むか。
    /// スキーマが変わった場合、古いDBファイルを残すとテーブル定義の不一致で画面が実行時エラーになる。
    /// ダミーデータ生成コードが変わった場合、DBはファイルが存在しないときだけ起動時に再作成されるため、
    /// 作り直さないと変更が反映されない。それ以外の変更ではユーザーが入力したデータを保持する。
    /// </summary>
    public bool RequiresDatabaseReset =>
        ChangedPaths.Contains(WorkspaceSourceSnapshot.SCHEMA_XML)
        || ChangedPaths.Any(path => Path.GetFileName(path).Contains("DummyDataGenerator", StringComparison.OrdinalIgnoreCase));
}
