import { createOpenRouter } from "@openrouter/ai-sdk-provider"
import { generateText, stepCountIs } from "ai"
import type { ProjectFiles } from "../ProjectFiles.ts"
import type { AgentCallOptions } from "./ChatTurn.ts"
import type { SessionContext } from "./SessionContext.ts"

/** 1回の調査あたりツール呼び出しを重ねてよい最大ステップ数 */
const MAX_RESEARCH_STEPS = 12

/**
 * ResearchAgent が回答の最後に必ず従うべき出力形式。3領域共通で強制する。
 * 「分からなかったこと」を空欄で済ませることを許すと、調査役が推測で埋めて
 * 主エージェントがそれを事実として受け取る事故が起きるため、最も念入りに指示する。
 */
const RESEARCH_OUTPUT_FORMAT = `
回答は必ず次の4項目で構成すること。
結論: 問いに対する答え。
根拠: 参照した実在のファイルパスと該当箇所。
分からなかったこと: 調べたが確定できなかった点。無いと決めつけず、確認できていないことは正直に書く。推測で埋めないこと。
次に調べるとよいこと: 他の調査領域（research_schema / research_code / research_screen）に引き継ぐとよい問い。無ければ「なし」と書く。
`.trim()

/**
 * 1つの調査領域の定義。担当領域（前提知識・探し始める場所）が違うだけで {@link ResearchAgent} の構造は完全に共通のため、
 * サブクラスやモジュールを増やさずデータとして持つ。
 */
export type ResearchDomain = {
  /** エージェントがツールとして公開する際の名前（例: research_schema） */
  toolName: string
  /** 主エージェントがこのツールをいつ使うべきかの説明。ツール定義の description にそのまま使う。 */
  description: string
  /** この領域の担当範囲・前提知識・探し始める場所を説明するシステムプロンプト本体を組み立てる。 */
  buildSystemPrompt: (context: SessionContext) => string
}

/**
 * 特定の知識領域に絞って調査を行うエージェント。担当領域は {@link ResearchDomain} で切り替える。
 * 主エージェント（RootAgent）とは別の会話・別のステップ予算で動き、要約テキスト1本だけを呼び出し元に返す。
 * 読んだファイル全文は親エージェントの会話履歴（ひいては永続化される current-state.json）には残らない。
 */
export class ResearchAgent {
  readonly #projectFiles: ProjectFiles
  readonly #domain: ResearchDomain

  constructor(projectFiles: ProjectFiles, domain: ResearchDomain) {
    this.#projectFiles = projectFiles
    this.#domain = domain
  }

  get toolName(): string {
    return this.#domain.toolName
  }

  get description(): string {
    return this.#domain.description
  }

  /**
   * 1件の問いを調査し、要約テキストで結果を返す。
   * RootAgent と違い最終ステップでツールを封じる prepareStep のガードが無いため、ステップ上限に達すると
   * 空文字や調査途中の断片を返しうる。それを RootAgent が事実として受け取る事故を防げるよう、
   * 上限到達・空回答は warn で必ず残す（{@link ResearchAgent.research} の呼び出し元からは result.text しか見えないため）。
   */
  async research(question: string, context: SessionContext, options: AgentCallOptions): Promise<string> {
    const openrouter = createOpenRouter({ apiKey: options.apiKey, compatibility: "strict" })
    const result = await generateText({
      model: openrouter.chat(options.model),
      system: `${this.#domain.buildSystemPrompt(context)}\n\n${RESEARCH_OUTPUT_FORMAT}`,
      prompt: question,
      tools: this.#projectFiles.buildAiTools(),
      stopWhen: stepCountIs(MAX_RESEARCH_STEPS),
      abortSignal: options.abortSignal,
      telemetry: { functionId: `research.${this.#domain.toolName.replace(/^research_/, "")}`, integrations: [options.turn] },
    })

    const steps = result.steps.length
    if (steps >= MAX_RESEARCH_STEPS) options.log.warn("research.capped", { agent: this.#domain.toolName, steps })
    if (result.text.trim() === "") options.log.warn("research.empty", { agent: this.#domain.toolName, steps })
    options.log.trace("research.answer", { agent: this.#domain.toolName, question, answer: result.text, steps })

    return result.text
  }
}

/** nijo.xml（データ構造・画面の元になるモデル定義）を担当する調査領域 */
export const SCHEMA_RESEARCH_DOMAIN: ResearchDomain = {
  toolName: "research_schema",
  description: "nijo.xmlに書かれているデータ構造を調査する。「どんな項目があるか」「項目の型・必須・一意制約」「どの画面がどのモデルから生成されるか」「ある業務概念がnijo.xml上どう表現されているか」を知りたいときに使う。",
  buildSystemPrompt: context => `
あなたは「${context.applicationName}」のデータ構造（nijo.xml）を調査する専門エージェントです。
主エージェントから来た問いに対し、実際のファイルを確認したうえで回答してください。憶測で答えないこと。

# 調べ方
- データ構造の定義はプロジェクトルート直下の nijo.xml 1ファイルにまとまっている。まずこれを読むこと。
- nijo.xml の記法（各属性 Type / IsKey / IsNotNull / UniqueConstraints などの意味、data-model / query-model 等モデル種類の違い）が分からない場合は、
  .claude/skills/nijo-system-design/references/20_model-catalog.md を読んで確認すること。
- 要素名・属性値は日本語（例: 商品, 売値単価_税抜）で、業務用語がそのままモデル定義になっている。grep で業務用語から探し始めるとよい。

# プロジェクトのフォルダ構成
${context.projectStructureOverview}
`.trim(),
}

/** C#で書かれたバックエンド（業務ロジック）を担当する調査領域 */
export const CODE_RESEARCH_DOMAIN: ResearchDomain = {
  toolName: "research_code",
  description: "C#で書かれたバックエンド（業務ロジック）の現状を調査する。「この業務処理は今どう動くか」「このルールはどこに書いてあるか」「自動生成の何を上書きしているか」を知りたいときに使う。",
  buildSystemPrompt: context => `
あなたは「${context.applicationName}」のバックエンド（C#）実装の現状を調査する専門エージェントです。
主エージェントから来た問いに対し、実際のファイルを確認したうえで回答してください。憶測で答えないこと。

# 前提知識
- Core: 手書きの業務ロジック。調査の中心になることが多い。配下は業務ドメイン別フォルダに分かれている
  （商品・入荷・売上・在庫調整・従業員・外部システム・ログイン認証 等）。grep で業務用語を検索して探し始めるとよい。
- Core.AutoGenerated: nijo.xml から Nijo が自動生成したコード。直接は編集しない生成物だが、
  実際に生成されているデータ構造・メソッドを確認する必要がある場合はここも読む。
- Overrided から始まるファイル（OverridedApplicationService, OverridedDbContext, OverridedDummyDataGenerator 等）は
  自動生成コードに対する拡張・上書きの入口。
- WebApi: HTTPとCoreの橋渡し。Management: 運用者向けコンソールアプリ。UnitTest: テストコード。

# プロジェクトのフォルダ構成
${context.projectStructureOverview}
`.trim(),
}

/** client配下の画面（React実装）と、利用者の言葉から実装上の名前への翻訳を担当する調査領域 */
export const SCREEN_RESEARCH_DOMAIN: ResearchDomain = {
  toolName: "research_screen",
  description: "利用者が画面を見ながら話している言葉（画面名・項目名・ボタン名）を実装上の名前に翻訳する、または画面（client配下のReact実装）自体の現状を調査する。プログラミングの素養がない利用者の発話は、まずこの調査から読み解き始めるとよい。",
  buildSystemPrompt: context => `
あなたは「${context.applicationName}」の画面（clientディレクトリのReact実装）の現状を調査する専門エージェントです。
主エージェントから来た問いに対し、実際のファイルを確認したうえで回答してください。憶測で答えないこと。

# 最重要の前提知識: 画面上のラベルの出所
利用者は「画面に見えている言葉」で話しかけてくることが多い（例:「商品コード」「一覧画面」）。
画面上のラベルは多くの場合 nijo.xml の DisplayName 属性から来ている
（例: nijo.xml上の要素名は「外部システム側ID」だが DisplayName="商品コード" のため画面には「商品コード」と表示される）。
利用者の言葉から実装上の要素名が分からない場合は、まず nijo.xml 側の DisplayName を grep で検索し、元の要素名を特定すること。

# clientディレクトリの前提知識
- client/src/__autoGenerated: nijo.xml から Nijo が自動生成した画面コード。直接は編集しない生成物。
- client/src/pages, client/src/routes.tsx: 手書きの画面コード。
- 「この画面はどのAPIを叩くか」を調べる場合は、該当コンポーネントの fetch / API呼び出し箇所を探す。

# プロジェクトのフォルダ構成
${context.projectStructureOverview}
`.trim(),
}
