import React, { useState } from "react"
import * as ReactRouter from "react-router-dom"
import { useNavigate } from "react-router-dom"
import { useForm, Controller } from "react-hook-form"
import { PageBase } from "../app/PageBase"
import { DataTable, DataTableColumn } from "../ui/DataTable"
import { PageTitle } from "../ui/PageTitle"
import { FormLabel } from "../ui/FormLabel"
import { CheckBox } from "../ui/CheckBox"
import { DateInput } from "../ui/DateInput"
import { DescriptionTextArea } from "../ui/DescriptionTextArea"
import { EnumSelection } from "../app/EnumSelection"
import { EnumSearchCondition } from "../app/EnumSearchCondition"
import { NumericTextBox } from "../ui/NumericTextBox"
import { WordTextBox } from "../ui/WordTextBox"
import { Button } from "../ui/Button"
import { NowLoading } from "../ui/NowLoading"
import * as EnumDefs from "../__autoGenerated/enum-defs"

const SampleIcon = ({ className }: { className?: string }) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className={className}>
    <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
  </svg>
)

export const URL = "/ui-component-catalog"

export function useNavigateToUIComponentCatalog() {
  const navigate = useNavigate()
  return React.useCallback(() => {
    navigate(URL)
  }, [navigate])
}

export default {
  path: URL,
  element: <UIComponentCatalog />,
} satisfies ReactRouter.RouteObject

function UIComponentCatalog() {
  // 各入力コンポーネントの状態管理用state
  type FormData = {
    checkBoxValue: boolean
    dateValue: string
    descValue: string
    enumValue: EnumDefs.売上明細区分 | null
    numValue: string
    wordValue: string
    enumSearchConditionValue: EnumDefs.消費税区分SearchCondition
  }

  const { register, control, watch } = useForm<FormData>({
    defaultValues: {
      checkBoxValue: false,
      dateValue: "",
      descValue: "",
      enumValue: null,
      numValue: "",
      wordValue: "",
      enumSearchConditionValue: {},
    }
  })
  const values = watch()

  const [loadingVisible, setLoadingVisible] = useState(false)

  // DataTable example data
  type TableRow = { id: number, name: string, price: number, category: string }
  const tableRows: TableRow[] = React.useMemo(() => Array.from({ length: 20 }).flatMap((_, i) => [
    { id: i * 10 + 1, name: "商品A", price: 1000, category: "食品" },
    { id: i * 10 + 2, name: "商品B", price: 2500, category: "家電" },
    { id: i * 10 + 3, name: "商品C", price: 500, category: "雑貨" },
    { id: i * 10 + 4, name: "商品D", price: 12000, category: "家電" },
    { id: i * 10 + 5, name: "商品E", price: 300, category: "食品" },
  ]), [])
  const tableColumns: DataTableColumn<TableRow>[] = [
    { header: "ID", render: row => row.id, widthPx: 60 },
    { header: "商品名", render: row => row.name },
    { header: "価格", render: row => <div className="text-right">{row.price.toLocaleString()}円</div>, widthPx: 100 },
    { header: "カテゴリ", render: row => <span className="px-2 py-1 bg-gray-200 rounded text-xs">{row.category}</span>, widthPx: 100 },
  ]

  return (
    <PageBase
      browserTitle="UIコンポーネントカタログ"
      header={<PageTitle>UIコンポーネントカタログ</PageTitle>}
      contents={
        <div className="p-4 space-y-8 pb-20">
          <section>
            <h2 className="text-xl font-bold mb-4 border-b">Button</h2>
            <div className="space-y-4 p-4 border rounded">
              <div className="flex flex-wrap gap-4 items-center">
                <Button onClick={() => alert('clicked')}>Default</Button>
                <Button fill onClick={() => alert('clicked')}>Fill</Button>
                <Button outline onClick={() => alert('clicked')}>Outline</Button>
                <Button underline onClick={() => alert('clicked')}>Underline</Button>
                <Button disabled onClick={() => alert('clicked')}>Disabled</Button>
              </div>
              <div className="flex flex-wrap gap-4 items-center">
                <Button mini onClick={() => alert('clicked')}>Mini</Button>
                <Button mini fill onClick={() => alert('clicked')}>Mini Fill</Button>
                <Button loading onClick={() => alert('clicked')}>Loading</Button>
                <Button fill loading onClick={() => alert('clicked')}>Loading Fill</Button>
              </div>
              <div className="flex flex-wrap gap-4 items-center">
                <Button icon={SampleIcon} onClick={() => alert('clicked')}>Icon</Button>
                <Button icon={SampleIcon} iconRight onClick={() => alert('clicked')}>Icon Right</Button>
                <Button icon={SampleIcon} hideText onClick={() => alert('clicked')}>Icon Only</Button>
                <Button icon={SampleIcon} fill onClick={() => alert('clicked')}>Icon Fill</Button>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-4 border-b">入力フォーム</h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {/* CheckBox */}
              <div className="space-y-2">
                <h3 className="font-bold">CheckBox</h3>
                <div className="p-4 border rounded">
                  <CheckBox
                    {...register("checkBoxValue")}
                  >
                    チェックボックス
                  </CheckBox>
                  <div className="text-sm text-gray-500 mt-2">Checked: {String(values.checkBoxValue)}</div>
                </div>
              </div>

              {/* DateInput */}
              <div className="space-y-2">
                <h3 className="font-bold">DateInput</h3>
                <div className="p-4 border rounded space-y-4">
                  <div>
                    <FormLabel>Date (default)</FormLabel>
                    <DateInput
                      {...register("dateValue")}
                    />
                  </div>
                  <div>
                    <FormLabel>DateTime</FormLabel>
                    <DateInput
                      appearance="datetime"
                    />
                  </div>
                  <div className="text-sm text-gray-500">Value: {values.dateValue}</div>
                </div>
              </div>

              {/* DescriptionTextArea */}
              <div className="space-y-2">
                <h3 className="font-bold">DescriptionTextArea</h3>
                <div className="p-4 border rounded">
                  <DescriptionTextArea
                    {...register("descValue")}
                    placeholder="複数行のテキストを入力..."
                    className="w-full"
                  />
                  <div className="text-sm text-gray-500 mt-2">Value: {values.descValue}</div>
                </div>
              </div>

              {/* EnumSelection */}
              <div className="space-y-2">
                <h3 className="font-bold">EnumSelection</h3>
                <div className="p-4 border rounded">
                  <FormLabel>売上明細区分</FormLabel>
                  <Controller
                    control={control}
                    name="enumValue"
                    render={({ field }) => (
                      <EnumSelection
                        type="売上明細区分"
                        {...field}
                      />
                    )}
                  />
                  <div className="text-sm text-gray-500 mt-2">Value: {values.enumValue}</div>
                </div>
              </div>

              {/* EnumSearchCondition */}
              <div className="space-y-2">
                <h3 className="font-bold">EnumSearchCondition</h3>
                <div className="p-4 border rounded">
                  <FormLabel>消費税区分</FormLabel>
                  <EnumSearchCondition
                    control={control}
                    name="enumSearchConditionValue"
                    type="消費税区分"
                  />
                  <div className="text-sm text-gray-500 mt-2">Value: {JSON.stringify(values.enumSearchConditionValue)}</div>
                </div>
              </div>

              {/* NumericTextBox */}
              <div className="space-y-2">
                <h3 className="font-bold">NumericTextBox</h3>
                <div className="p-4 border rounded space-y-4">
                  <div>
                    <FormLabel>通常</FormLabel>
                    <NumericTextBox
                      {...register("numValue")}
                      integerDigit={6}
                      decimalDigit={2}
                    />
                  </div>
                  <div>
                    <FormLabel>3桁カンマ区切り (commaSeparated)</FormLabel>
                    <NumericTextBox
                      commaSeparated
                      defaultValue="1,234,567"
                      integerDigit={7}
                      prefix="¥"
                      suffix="万円"
                      className="w-40"
                    />
                  </div>
                  <div className="text-sm text-gray-500">Value: {values.numValue}</div>
                </div>
              </div>

              {/* WordTextBox */}
              <div className="space-y-2">
                <h3 className="font-bold">WordTextBox</h3>
                <div className="p-4 border rounded">
                  <FormLabel>単語入力 (自動trim, NFKC正規化)</FormLabel>
                  <WordTextBox
                    {...register("wordValue")}
                  />
                  <div className="text-sm text-gray-500 mt-2">Value: {values.wordValue}</div>
                </div>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-4 border-b">Layout Components</h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {/* FormLabel */}
              <div className="space-y-2">
                <h3 className="font-bold">FormLabel</h3>
                <div className="p-4 border rounded">
                  <FormLabel>これはフォームラベルです</FormLabel>
                  <div className="mt-1 p-2 bg-gray-100 rounded text-sm">入力フォームの項目名などに使用します</div>
                </div>
              </div>

              {/* PageTitle */}
              <div className="space-y-2">
                <h3 className="font-bold">PageTitle</h3>
                <div className="p-4 border rounded">
                  <PageTitle>ページタイトル</PageTitle>
                  <div className="mt-1 p-2 bg-gray-100 rounded text-sm">画面左上のタイトルとして使用します</div>
                </div>
              </div>

              {/* NowLoading */}
              <div className="space-y-2">
                <h3 className="font-bold">NowLoading</h3>
                <div className="p-4 border rounded relative h-40">
                  <button
                    className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
                    onClick={() => {
                      setLoadingVisible(true)
                      setTimeout(() => setLoadingVisible(false), 2000)
                    }}
                  >
                    ローディングを表示 (2秒間)
                  </button>
                  <div className="mt-4">
                    ローディングコンポーネントは親要素(relative)の全面を覆います。
                  </div>
                  {loadingVisible && <NowLoading />}
                </div>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-4 border-b">DataTable</h2>
            <div className="space-y-2">
              <div className="p-4 border rounded">
                <DataTable
                  rows={tableRows}
                  columns={tableColumns}
                  className="w-full max-h-60 resize-x border border-gray-700"
                />
                <div className="mt-2 text-sm text-gray-500">
                  シンプルなテーブルコンポーネント。ヘッダ固定、横スクロール対応。
                </div>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-4 border-b">Page Layouts (Description Only)</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>PageBase</strong>: 汎用的なページレイアウト。ヘッダー、フッター、コンテンツエリアを提供します。</li>
              <li><strong>SearchPageBase</strong>: 検索画面用のレイアウト。検索条件エリア、検索結果エリア、ページング機能を提供します。</li>
              <li><strong>EditPageBase</strong>: 編集画面用のレイアウト。保存処理、ダーティチェック（未保存警告）などを提供します。</li>
              <li><strong>RootLayout</strong>: アプリケーション全体のルートレイアウト。サイドメニューやグローバルナビゲーションを含みます。</li>
            </ul>
          </section>
        </div>
      }
    />
  )
}

