import React from "react"
import * as ReactHookForm from "react-hook-form"
import { MultiSelect } from "../../ui/MultiSelect"
import { QueryModelType, SearchCondition, ASC_SUFFIX, DESC_SUFFIX } from "../../__autoGenerated"

export type SortComboItem<TQueryModelType extends QueryModelType> = {
  key: SearchCondition.SortableMemberTypeMap[TQueryModelType]
  label: string
}

type SortComboItemWithAscDesc<TQueryModelType extends QueryModelType> = {
  key: SearchCondition.TypeMap[TQueryModelType]['sort'][number]
  label: string
}

export type SearchPageSortDropdownProps<
  TQueryModelType extends QueryModelType,
  TCondition extends SearchCondition.TypeMap[TQueryModelType] & ReactHookForm.FieldValues
> = {
  className?: string
  sortOptions?: SortComboItem<TQueryModelType>[]
  control: ReactHookForm.Control<TCondition>
  pageSize: number
  getValues: ReactHookForm.UseFormGetValues<TCondition>
  setValue: ReactHookForm.UseFormSetValue<TCondition>
  applyConditionToUrl: (nextCondition: TCondition) => void
}

/**
 * 検索ページのソート順指定ドロップダウン
 */
export function SearchPageSortDropdown<
  TQueryModelType extends QueryModelType,
  TCondition extends SearchCondition.TypeMap[TQueryModelType] & ReactHookForm.FieldValues
>(props: SearchPageSortDropdownProps<TQueryModelType, TCondition>) {
  const {
    className,
    sortOptions: providedSortOptions,
    control,
    pageSize,
    getValues,
    setValue,
    applyConditionToUrl,
  } = props

  const sortOptions = React.useMemo(() => providedSortOptions ?? [], [providedSortOptions])

  const sortValue = ReactHookForm.useWatch({
    control,
    name: 'sort' as ReactHookForm.FieldPath<TCondition>,
  }) as TCondition['sort'] | undefined

  const resolvedSortValue = sortValue ?? ([] as TCondition['sort'])

  const sortComboOptionsWithAscDesc = React.useMemo((): SortComboItemWithAscDesc<TQueryModelType>[] => {
    if (sortOptions.length === 0) {
      return []
    }
    const asc = '（昇順）' satisfies ASC_SUFFIX
    const desc = '（降順）' satisfies DESC_SUFFIX
    const selectedKeysWithoutAscDesc = new Set(resolvedSortValue.map(key => {
      if (key.endsWith(asc)) {
        return key.slice(0, -asc.length)
      }
      if (key.endsWith(desc)) {
        return key.slice(0, -desc.length)
      }
      return key
    }))
    return sortOptions
      .filter(item => !selectedKeysWithoutAscDesc.has(item.key))
      .flatMap(item => [
        { key: item.key + asc, label: item.label + ' (昇順)' },
        { key: item.key + desc, label: item.label + ' (降順)' },
      ]) as SortComboItemWithAscDesc<TQueryModelType>[]
  }, [sortOptions, resolvedSortValue])

  const sortValueAsComboItem = React.useMemo((): SortComboItemWithAscDesc<TQueryModelType>[] => {
    if (sortOptions.length === 0) {
      return []
    }
    const labelMap = new Map<string, string>(sortOptions.flatMap(item => [
      [item.key + ('（昇順）' satisfies ASC_SUFFIX), item.label + ' (昇順)'],
      [item.key + ('（降順）' satisfies DESC_SUFFIX), item.label + ' (降順)'],
    ]))
    return resolvedSortValue.map(key => ({
      key,
      label: labelMap.get(key) ?? key,
    }))
  }, [resolvedSortValue, sortOptions])

  const handleSortChange = React.useCallback((newSort: SortComboItemWithAscDesc<TQueryModelType>[]) => {
    const newValue = newSort.map(item => item.key) as TCondition['sort']
    setValue('sort' as ReactHookForm.FieldPath<TCondition>, newValue, { shouldDirty: true })
    const current = getValues()
    const nextCondition = {
      ...current,
      sort: newValue,
      skip: '0',
      take: pageSize.toString(),
    } as TCondition
    applyConditionToUrl(nextCondition)
  }, [applyConditionToUrl, getValues, pageSize, setValue])

  if (sortOptions.length === 0) {
    return null
  }

  return (
    <MultiSelect<SortComboItemWithAscDesc<TQueryModelType>>
      className={className}
      value={sortValueAsComboItem}
      options={sortComboOptionsWithAscDesc}
      onChange={handleSortChange}
      getLabel={item => item.label}
      placeholder="並び順"
    />
  )
}
