import { ApplicationRoot } from './__autoGenerated/application'
import { UserInputテスト } from './debug-room/UserInputテスト'

function App() {

  return (
    <ApplicationRoot />
    // <UserInputテスト />
  )
}

export default App
