// import { DefaultNijoApp } from './__autoGenerated'
import UserInputテスト from './debug-room/UserInputテスト'
// import BatchUpdateテスト from './debug-room/BatchUpdateテスト'
// import VFormテスト from './debug-room/VFromテスト'

function App() {

  return (
    // <DefaultNijoApp />
    <UserInputテスト />
    // <BatchUpdateテスト />
    // <VFormテスト />
  )
}

export default App
