@DevTool.Server_HostAddress = http://localhost:5184

### デバッグ実行のプロセス群を起動する（全プロセス）
POST {{DevTool.Server_HostAddress}}/devtool-api/preview/start

### デバッグ実行のプロセス群を起動する（vite のみ）
POST {{DevTool.Server_HostAddress}}/devtool-api/preview/start?process=vite

### デバッグ実行のプロセス群の稼働状態とログ増分を取得する
POST {{DevTool.Server_HostAddress}}/devtool-api/preview/state
Content-Type: application/json

{
  "offsets": {
    "vite": { "stdout": 0, "stderr": 0 },
    "dotnet": { "stdout": 0, "stderr": 0 }
  }
}

### デバッグ実行のプロセス群を再起動する（全プロセス）
POST {{DevTool.Server_HostAddress}}/devtool-api/preview/restart

### デバッグ実行のプロセス群を再起動する（dotnet のみ）
POST {{DevTool.Server_HostAddress}}/devtool-api/preview/restart?process=dotnet

### デバッグ実行のプロセス群を停止する（全プロセス）
POST {{DevTool.Server_HostAddress}}/devtool-api/preview/stop

###
