using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System;
using System.Reflection;
using System.Text;

namespace Nijo.IntegrationTest {
    /// <summary>
    /// 自動テストで作成されたプロジェクト。テスト全体で共有する
    /// </summary>
    [SetUpFixture]
    public class TestProject {

#pragma warning disable CS8618 // null 非許容のフィールドには、コンストラクターの終了時に null 以外の値が入っていなければなりません。Null 許容として宣言することをご検討ください。
        public static GeneratedProject Current { get; private set; }
#pragma warning restore CS8618 // null 非許容のフィールドには、コンストラクターの終了時に null 以外の値が入っていなければなりません。Null 許容として宣言することをご検討ください。

        #region SETUP
        [OneTimeSetUp]
        public void SetUp() {
            var serviceProvider = Util.ConfigureServices();
            var logger = serviceProvider.GetRequiredService<ILogger>();

            // 出力が文字化けするので
            Console.OutputEncoding = Encoding.UTF8;

            // 依存先パッケージのインストールにかかる時間とデータ量を削減するために全テストで1つのディレクトリを共有する
            const string DIR_NAME = "自動テストで作成されたプロジェクト";
            var dir = Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), "..", "..", "..", "..", DIR_NAME));
            Current = Directory.Exists(dir)
                ? GeneratedProject.Open(dir, serviceProvider, logger)
                : GeneratedProject.Create(dir, DIR_NAME, true, serviceProvider, log: logger);
        }

        [OneTimeTearDown]
        public void TearDown() {

        }
        #endregion SETUP


        #region LAUNCH
        /// <summary>
        /// 引数のデータパターンでテストプロジェクトを構築し、アプリケーションを実行します。
        /// </summary>
        public static async Task<Task> LaunchWebApiAndClient(DataPattern dataPattern, CancellationToken cancellationToken) {
            // コードを再作成
            File.WriteAllText(Current.SchemaXml.GetPath(), dataPattern.LoadXmlString());
            Current.CodeGenerator.UpdateAutoGeneratedCode();
            await Current.Debugger.BuildAsync(cancellationToken, GeneratedProjectDebugger.E_NpmBuild.None);

            // 開始
            var dotnetRun = await Current.Debugger.CreateServerRunningProcess(cancellationToken);
            var npmStart = await Current.Debugger.CreateClientRunningProcess(cancellationToken);

            return Task.WhenAll(dotnetRun, npmStart);
        }

        /// <summary>
        /// 実行中のテスト用プロジェクトをWebから操作する機構を作成します。
        /// </summary>
        public static IWebDriver CreateWebDriver() {
            var exeDir = Assembly.GetExecutingAssembly().Location;
            var driver = new ChromeDriver(exeDir);
            try {

                // トップページに移動する
                var root = Current.Debugger.GetDebuggingClientUrl();
                driver.Navigate().GoToUrl(root);

                return driver;

            } catch {
                driver.Dispose();
                throw;
            }
        }
        #endregion LAUNCH
    }
}
