using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.WebApi.Base; // PresentationContextInWebApi と JsonUtil のため
using Microsoft.AspNetCore.Mvc.Controllers;

namespace MyApp.Core;

public class AutoGeneratedModelBinderProvider : IModelBinderProvider {
    public IModelBinder? GetBinder(ModelBinderProviderContext context) {
        ArgumentNullException.ThrowIfNull(context);

        var modelType = context.Metadata.ModelType;

        // IPresentationContext<TMessageRoot> 型の引数か判定
        if (modelType.IsGenericType && modelType.GetGenericTypeDefinition() == typeof(IPresentationContext<>)) {
            var messageRootType = modelType.GetGenericArguments()[0];
            var binderType = typeof(ContextModelBinder<>).MakeGenericType(messageRootType);
            return (IModelBinder?)Activator.CreateInstance(binderType);
        }

        // カスタムバインダーを使用するモデルかどうかを判定
        // ExecuteSqlRequestなど、特定のコントローラーだけで使われる型は除外し、
        // 通常のモデルバインダーに処理を任せる
        if (typeof(DebuggingController.ExecuteSqlRequest).IsAssignableFrom(modelType)) {
            return null; // 標準のモデルバインディングに任せる
        }

        // それ以外のモデルに対してはDataModelBinderを適用
        var dataBinderType = typeof(DataModelBinder<>).MakeGenericType(modelType);
        return (IModelBinder?)Activator.CreateInstance(dataBinderType);
    }
}

// data パラメータ用モデルバインダ
public class DataModelBinder<TParameter> : IModelBinder {
    public Task BindModelAsync(ModelBindingContext bindingContext) {
        ArgumentNullException.ThrowIfNull(bindingContext);

        var request = bindingContext.HttpContext.Request;

        // multipart/form-data の場合、特定のフォームフィールドからJSONを取得
        if (request.HasFormContentType && request.Form.TryGetValue("complex-post-request-body", out var dataSection)) {
            if (!string.IsNullOrEmpty(dataSection)) {
                try {
                    var jsonOptions = JsonUtil.GetDefaultJsonSerializerOptions();
                    var data = JsonSerializer.Deserialize<TParameter>(dataSection.ToString(), jsonOptions);
                    if (data != null) {
                        bindingContext.Result = ModelBindingResult.Success(data);
                        return Task.CompletedTask;
                    }
                } catch (JsonException ex) {
                    bindingContext.ModelState.AddModelError(bindingContext.ModelName, $"JSON deserialization error: {ex.Message}");
                    bindingContext.Result = ModelBindingResult.Failed();
                    return Task.CompletedTask;
                }
            }
        }

        // 上記以外（例: application/json）の場合、リクエストボディ全体をデシリアライズ
        // 注: デフォルトの BodyModelBinder と競合する可能性があるため、
        //     Controller 側で [FromBody] 属性を明示しない等の注意が必要になる場合があります。
        //     ここでは一旦、上記 multipart/form-data のケースのみを優先的に処理します。
        //     もし application/json 等もこのバインダーで処理したい場合は、以下のようなロジックを追加します。
        /*
        else if (request.ContentType?.StartsWith("application/json", StringComparison.OrdinalIgnoreCase) == true) {
            try {
                using var reader = new StreamReader(request.Body);
                var body = await reader.ReadToEndAsync();
                if (!string.IsNullOrEmpty(body)) {
                    var jsonOptions = JsonUtil.GetDefaultJsonSerializerOptions();
                    var data = JsonSerializer.Deserialize<TParameter>(body, jsonOptions);
                    if (data != null) {
                        bindingContext.Result = ModelBindingResult.Success(data);
                        return;
                    }
                }
            } catch (JsonException ex) {
                bindingContext.ModelState.AddModelError(bindingContext.ModelName, $"JSON deserialization error: {ex.Message}");
                bindingContext.Result = ModelBindingResult.Failed();
                return;
            }
        }
        */

        // バインドできなかった場合
        bindingContext.Result = ModelBindingResult.Failed();

        return Task.CompletedTask;
    }
}

// context パラメータ用モデルバインダ
public class ContextModelBinder<TMessageRoot> : IModelBinder where TMessageRoot : IMessageContainer {
    public Task BindModelAsync(ModelBindingContext bindingContext) {
        ArgumentNullException.ThrowIfNull(bindingContext);

        var httpContext = bindingContext.HttpContext;

        // `useHttpRequest` フック内でこの名前のクエリパラメータが付される
        const string PARAM_IGNORE_CONFIRM = "ignore-confirm";
        bool blnIgnoreConfirm;
        if (!httpContext.Request.Query.TryGetValue(PARAM_IGNORE_CONFIRM, out var strIgnoreConfirm)) {
            blnIgnoreConfirm = false;
        } else if (!bool.TryParse(strIgnoreConfirm, out var b)) {
            blnIgnoreConfirm = false;
        } else {
            blnIgnoreConfirm = b;
        }

        // PresentationContext のインスタンス作成
        var presentationContextOptions = new PresentationContextOptions {
            IgnoreConfirm = blnIgnoreConfirm,
        };
        // TMessageRoot のデフォルトインスタンスを取得する処理は GetDefaultClass を使う想定
        var messages = MessageContainer.GetDefaultClass<TMessageRoot>([]);
        var presentationContext = new PresentationContextInWebApi<TMessageRoot>(messages, presentationContextOptions);

        bindingContext.Result = ModelBindingResult.Success(presentationContext);
        return Task.CompletedTask;
    }
}
