using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Util.CodeGenerating {
    /// <summary>
    /// NijoApplicationBuilderが自動生成するソースコードが要件を満たさない場合のために、
    /// 自動生成されるソースコードを自由に改変するためのインターフェース
    /// </summary>
    public interface IAutoGeneratedCodeCustomizer {
        /// <summary>
        /// 自動生成されるソースコードを改変します。
        /// </summary>
        /// <param name="context">
        /// コード生成コンテキスト。
        /// このオブジェクトのメソッドを通してソースコードを改変してください。
        /// </param>
        void CustomizeAutoGeneratedCode(CodeRenderingContext context);
    }
}
