using Nijo.Util.CodeGenerating;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Parts.WebClient {
    /// <summary>
    /// nijo-default-style.css ファイル
    /// </summary>
    internal class NijoDefaultStyleCss {

        /// <summary>
        /// 既定のCSSファイルを編集します。
        /// </summary>
        internal static SourceFile Generate(EmbeddedResource.Collection embeddedResources) => new SourceFile {
            FileName = "nijo-default-style.css",
            RenderContent = ctx => {

                // テンプレートアプリケーションのCSS
                var resource = embeddedResources.Get("react", "src", "__autoGenerated", "nijo-default-style.css");
                using var reader = resource.GetStreamReader();

                return $$"""
                    {{reader.ReadToEnd()}}
                    {{VerticalFormBuilder.RenderContainerQuery()}}
                    """;
            },
        };
    }
}
