using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Reflection;

namespace HalApplicationBuilder.Core {
    public class Aggregate {

        internal Aggregate() { }

        internal ApplicationSchema Schema { get; init; }
        internal Type UnderlyingType { get; init; }

        public string Name => UnderlyingType.Name;


        #region リレーション
        public IAggregateMember Parent { get; init; }

        private List<IAggregateMember> _members;
        public IReadOnlyList<IAggregateMember> Members {
            get {
                if (_members == null) {
                    _members = Schema.MemberFactory.CreateMembers(this).ToList();
                }
                return _members;
            }
        }

        public Aggregate GetRoot() {
            var aggregate = this;
            while (aggregate.Parent != null) {
                aggregate = aggregate.Parent.Owner;
            }
            return aggregate;
        }
        public IEnumerable<Aggregate> GetDescendants() {
            var children = Members.SelectMany(member => member.GetChildAggregates());
            foreach (var child in children) {
                yield return child;
                foreach (var descendant in child.GetDescendants()) {
                    yield return descendant;
                }
            }
        }
        #endregion リレーション


        #region CodeGenerating
        internal AutoGenerateDbEntityClass ToDbTableModel() {
            // 集約で定義されているカラム
            var pk = Members
                .Where(member => member.IsPrimaryKey)
                .SelectMany(member => member.ToDbColumnModel())
                .ToList();
            var notPk = Members
                .Where(member => !member.IsPrimaryKey)
                .SelectMany(member => member.ToDbColumnModel())
                .ToList();
            // 連番
            if (Parent != null && Parent.IsCollection && pk.Count == 0) {
                pk.Insert(0, new AutoGenerateDbEntityProperty {
                    Virtual = false,
                    CSharpTypeName = "int",
                    PropertyName = $"{Name}_連番",
                    Initializer = null,
                });
            }
            // 親の主キー
            if (Parent != null) {
                pk.InsertRange(0, Parent.Owner.ToDbTableModel().PKColumns);
                // stack overflow
                //_navigationProperties = new() {
                //    new Dto.PropertyTemplate { CSharpTypeName = $"virtual {Parent.Owner.ToDbTableModel().ClassName}", PropertyName = "Parent" },
                //};
            }

            var className = UnderlyingType.GetCustomAttribute<TableAttribute>()?.Name
                ?? UnderlyingType.Name;
            var fullname = Schema.Config.EntityNamespace + "." + className;

            return new AutoGenerateDbEntityClass {
                ClassName = className,
                RuntimeFullName = fullname,
                PKColumns = pk,
                NotPKColumns = notPk,
            };
        }
        #endregion CodeGenerating


        #region Runtime

        #endregion Runtime


        public override string ToString() {
            var path = new List<string>();
            var parent = Parent;
            while (parent != null) {
                path.Insert(0, parent.Name);
                parent = parent.Owner.Parent;
            }
            path.Insert(0, GetRoot().Name);
            return $"{nameof(Aggregate)}[{string.Join(".", path)}]";
        }
    }

    partial class AggregateVerticalViewTemplate {
        internal IEnumerable<KeyValuePair<string, string>> Members { get; set; }
    }
}
