export * from './menu'
export * from './application'
export * from './collection'
export * from './input'
export * from './util'

import '../__autoGenerated/nijo.css'

export const THIS_APPLICATION_NAME = 'サンプルアプリケーション' as const
