using Nijo.CodeGenerating;
using Nijo.ImmutableSchema;
using Nijo.Parts.Common;
using Nijo.Util.DotnetEx;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nijo.Parts.CSharp {
    public class AspNetController {
        public AspNetController(RootAggregate rootAggregate) {
            _rootAggregate = rootAggregate;
        }

        private readonly RootAggregate _rootAggregate;

        private const string API_SUBDOMAIN = "api";

        /// <summary>
        /// RootAttributeの引数に指定するルーティング定義
        /// </summary>
        public string Route => $"{API_SUBDOMAIN}/{_rootAggregate.LatinName.ToKebabCase()}";
        /// <summary>
        /// ASP.NET Core コントローラークラス名
        /// </summary>
        public string CsClassName => $"{_rootAggregate.PhysicalName}Controller";

        /// <summary>
        /// Webクライアント側からアクセスするときのAction名を返す。
        /// </summary>
        /// <param name="action">Action名単体</param>
        /// <returns>URLのドメイン部分を除いたサブドメイン部分</returns>
        public string GetActionNameForClient(string action) {
            return $"{Route}/{action}";
        }


        #region ASP.NET Core のバインディング設定
        private const string PARSE_COMPLEX_REQUEST_BODY_ASYNC = "ParseComplexRequestBodyAsync";
        private const string INITIALIZE_PRESENTATION_CONTEXT = "InitializePresentationContextAsync";
        private const string ON_AUTOGENERATED_ACTION_EXECUTED = "OnAutoGeneratedActionExecuted";
        private const string ON_AUTOGENERATED_ACTION_AUTHORIZATION = "OnAutoGeneratedActionAuthorization";
        private const string AUTOGENERATED_ACTION_METADATA = "AutoGeneratedActionMetadata";
        internal const string PRESENTATION_CONTEXT_BINDER = "PresentationContextModelBinder";
        internal const string COMPLEX_REQUEST_BODY_BINDER = "ComplexPostRequestBodyBinder";
        internal const string TO_ACTION_RESULT = "ToActionResult";

        internal const string AUTOGENERATED_ENDPOINT = "AutoGeneratedEndpoint";

        /// <summary>
        /// Actionの第1引数の名前
        /// </summary>
        internal const string DATA = "data";
        /// <summary>
        /// Actionの第2引数の名前
        /// </summary>
        internal const string CONTEXT = "context";

        /// <summary>
        /// 自動生成されたActionに付されるアトリビュート
        /// </summary>
        internal static SourceFile RenderAutoGeneratedEndpointAttribute(CodeRenderingContext ctx) {
            var className = $"{AUTOGENERATED_ENDPOINT}Attribute";

            return new SourceFile {
                FileName = "AutoGeneratedEndpointAttribute.cs",
                Contents = $$"""
                    using System;
                    using System.Reflection;
                    using Microsoft.AspNetCore.Mvc;
                    using Microsoft.AspNetCore.Mvc.Filters;

                    namespace {{ctx.Config.RootNamespace}};

                    /// <summary>
                    /// 自動生成されたエンドポイントのHTTPリクエスト・レスポンスの処理を定義します。
                    /// </summary>
                    public sealed class {{className}} : Attribute, IAuthorizationFilter, IActionFilter {
                        public {{className}}({{CommandQueryMappings.E_COMMAND_QUERY_TYPE}} modelType, {{E_AutoGeneratedActionType.ENUM_NAME}} readWrite) {
                            _metadata = new() {
                                ModelType = modelType,
                                ReadWrite = readWrite,
                            };
                        }

                        private readonly {{AUTOGENERATED_ACTION_METADATA}} _metadata;

                        /// <summary>
                        /// <see cref="{{ApplicationConfigure.ABSTRACT_CLASS_WEBAPI}}"/> で定義された認証ロジックを呼び出す。
                        /// </summary>
                        void IAuthorizationFilter.OnAuthorization(AuthorizationFilterContext context) {
                            var configure = context.HttpContext.RequestServices
                                .GetRequiredService<{{ApplicationConfigure.ABSTRACT_CLASS_WEBAPI}}>();
                            configure.{{ON_AUTOGENERATED_ACTION_AUTHORIZATION}}(context, _metadata);
                        }

                        /// <summary>
                        /// HTTPリクエストの内容を解釈し、自動生成されたControllerのActionの引数を組み立てる。
                        /// </summary>
                        void IActionFilter.OnActionExecuting(ActionExecutingContext context) {
                            // モデルバインダでメタデータが必要になる場合に備えて HttpContext.Items に格納しておく
                            context.HttpContext.Items[typeof({{AUTOGENERATED_ACTION_METADATA}})] = _metadata;
                        }

                        /// <summary>
                        /// 自動生成されたControllerのActionの実行後処理。
                        /// </summary>
                        void IActionFilter.OnActionExecuted(ActionExecutedContext context) {
                            var configure = context.HttpContext.RequestServices
                                .GetRequiredService<{{ApplicationConfigure.ABSTRACT_CLASS_WEBAPI}}>();
                            configure.{{ON_AUTOGENERATED_ACTION_EXECUTED}}(context, _metadata);
                        }
                    }

                    """,
            };
        }
        /// <summary>
        /// 自動生成されたActionのメタデータ
        /// </summary>
        internal static SourceFile RenderAutoGeneratedEndpointMetadata(CodeRenderingContext ctx) {
            return new SourceFile {
                FileName = "AutoGeneratedActionMetadata.cs",
                Contents = $$"""
                    using System;
                    using System.Reflection;
                    using Microsoft.AspNetCore.Mvc;
                    using Microsoft.AspNetCore.Mvc.Filters;

                    namespace {{ctx.Config.RootNamespace}};

                    /// <summary>
                    /// 自動生成されたアクションのメタデータ
                    /// </summary>
                    public sealed class {{AUTOGENERATED_ACTION_METADATA}} {
                        /// <summary>どの種類のモデルに対して発生したリクエストか</summary>
                        public required {{CommandQueryMappings.E_COMMAND_QUERY_TYPE}} ModelType { get; init; }
                        /// <summary>更新系処理、参照系処理の別</summary>
                        public required {{E_AutoGeneratedActionType.ENUM_NAME}} ReadWrite { get; init; }
                    }
                    """,
            };
        }
        /// <summary>
        /// PresentationContext のモデルバインディング
        /// </summary>
        internal static SourceFile RenderPresentationContextModelBinder(CodeRenderingContext ctx) {
            return new SourceFile {
                FileName = "PresentationContextModelBinder.cs",
                Contents = $$"""
                    using Microsoft.AspNetCore.Mvc.Controllers;
                    using Microsoft.AspNetCore.Mvc.ModelBinding;
                    using Microsoft.Extensions.DependencyInjection;
                    using System;
                    using System.IO;
                    using System.Text.Json;
                    using System.Threading.Tasks;

                    namespace {{ctx.Config.RootNamespace}};

                    /// <summary>
                    /// PresentationContext のモデルバインディング
                    /// </summary>
                    public sealed class {{PRESENTATION_CONTEXT_BINDER}}<TMessageRoot> : IModelBinder where TMessageRoot : {{MessageContainer.INTERFACE}} {
                        public async Task BindModelAsync(ModelBindingContext bindingContext) {
                            ArgumentNullException.ThrowIfNull(bindingContext);

                            var actionMetadata = ({{AUTOGENERATED_ACTION_METADATA}})bindingContext.HttpContext.Items[typeof({{AUTOGENERATED_ACTION_METADATA}})]!;
                            var configuration = bindingContext.HttpContext.RequestServices.GetRequiredService<{{ApplicationConfigure.ABSTRACT_CLASS_WEBAPI}}>();

                            // 詳細なロジックは自動生成されないメソッドに譲る
                            var presentationContext = await configuration.{{INITIALIZE_PRESENTATION_CONTEXT}}<TMessageRoot>(bindingContext, actionMetadata);

                            bindingContext.Result = ModelBindingResult.Success(presentationContext);
                        }
                    }
                    """,
            };
        }
        /// <summary>
        /// ComplexPost のリクエストボディのモデルバインディング
        /// </summary>
        internal static SourceFile RenderComplexPostRequestBodyModelBinder(CodeRenderingContext ctx) {
            return new SourceFile {
                FileName = "ComplexPostRequestBodyModelBinder.cs",
                Contents = $$"""
                    using Microsoft.AspNetCore.Mvc.Controllers;
                    using Microsoft.AspNetCore.Mvc.ModelBinding;
                    using Microsoft.Extensions.DependencyInjection;
                    using System;
                    using System.IO;
                    using System.Text.Json;
                    using System.Threading.Tasks;

                    namespace {{ctx.Config.RootNamespace}};

                    /// <summary>
                    /// ComplexPost のリクエストボディのインスタンスを作成するメソッドを呼び出すだけのモデルバインディング
                    /// </summary>
                    public sealed class {{COMPLEX_REQUEST_BODY_BINDER}}<TParameter> : IModelBinder {
                        public async Task BindModelAsync(ModelBindingContext bindingContext) {
                            ArgumentNullException.ThrowIfNull(bindingContext);

                            var actionMetadata = ({{AUTOGENERATED_ACTION_METADATA}})bindingContext.HttpContext.Items[typeof({{AUTOGENERATED_ACTION_METADATA}})]!;
                            var configuration = bindingContext.HttpContext.RequestServices.GetRequiredService<{{ApplicationConfigure.ABSTRACT_CLASS_WEBAPI}}>();

                            // 詳細なロジックは自動生成されないメソッドに譲る
                            var presentationContext = await configuration.{{PARSE_COMPLEX_REQUEST_BODY_ASYNC}}<TParameter>(bindingContext, actionMetadata);

                            bindingContext.Result = ModelBindingResult.Success(presentationContext);
                        }
                    }
                    """,
            };
        }

        internal static void RegisterWebapiConfiguration(IMultiAggregateSourceFileManager ctx) {
            ctx.Use<ApplicationConfigure>()
                //.AddControllers(option => $$"""
                //    {{option}}.ModelBinderProviders.Add(new {{MODEL_BINDER_BASE}}(this));
                //    """)
                .AddWebapiMethod($$"""
                    /// <summary>
                    /// 自動生成されたASP.NET Core の Action の実行前処理。
                    /// クライアント側から送られてきたリクエストを解釈し、具象型を返す。
                    /// 具体的な処理はアプリケーション毎に異なるため抽象メソッドとしている。
                    /// </summary>
                    /// <typeparam name="TParameter">パラメータのデータ型</typeparam>
                    /// <param name="bindingContext">ASP.NET Core が提供するモデルバインディングの仕組みが提供する情報。</param>
                    /// <param name="metadata">NijoApplicationBuilderが提供するメタ情報</param>
                    /// <returns>クライアント側から送られてきた処理の引数のインスタンス。</returns>
                    public abstract Task<TParameter> {{PARSE_COMPLEX_REQUEST_BODY_ASYNC}}<TParameter>(ModelBindingContext bindingContext, {{AUTOGENERATED_ACTION_METADATA}} metadata);
                    """)
                .AddWebapiMethod($$"""
                    /// <summary>
                    /// ComplexPostリクエストの開始時に呼ばれる。
                    /// <see cref="{{PresentationContext.INTERFACE}}{T}"/> を具備したクラスのインスタンスを初期化して返す。
                    /// </summary>
                    /// <typeparam name="TMessageRoot">パラメータのデータ型（≒画面のデータ型）と対応するエラーメッセージの入れ物の型</typeparam>
                    /// <param name="bindingContext">ASP.NET Core が提供するモデルバインディングの仕組みが提供する情報。</param>
                    /// <param name="metadata">NijoApplicationBuilderが提供するメタ情報</param>
                    public abstract Task<{{PresentationContext.INTERFACE}}<TMessageRoot>> {{INITIALIZE_PRESENTATION_CONTEXT}}<TMessageRoot>(ModelBindingContext bindingContext, {{AUTOGENERATED_ACTION_METADATA}} metadata) where TMessageRoot : {{MessageContainer.INTERFACE}};
                    """)
                .AddWebapiMethod($$"""
                    /// <summary>
                    /// 自動生成されたASP.NET Core の Action の実行後処理。
                    /// <see cref="{{PresentationContext.INTERFACE}}"/> の内容を <see cref="IActionResult"/> に変換する。
                    /// 具体的な処理はアプリケーション毎に異なるため抽象メソッドとしている。
                    /// </summary>
                    /// <typeparam name="TMessageRoot">パラメータのデータ型（≒画面のデータ型）と対応するエラーメッセージの入れ物の型</typeparam>
                    /// <param name="returnValue">処理の戻り値</param>
                    /// <param name="presentationContext">サーバー側で行なわれた一連の処理（登録処理など）の結果を保持しているオブジェクト</param>
                    /// <returns><see cref="IActionResult"/> のインスタンス。</returns>
                    public abstract IActionResult {{TO_ACTION_RESULT}}<TMessageRoot>(
                        object? returnValue,
                        {{PresentationContext.INTERFACE}}<TMessageRoot> presentationContext)
                        where TMessageRoot : {{MessageContainer.INTERFACE}};
                    """)
                .AddWebapiMethod($$"""
                    /// <summary>
                    /// 自動生成されたASP.NET Core の Action の実行後処理。
                    /// </summary>
                    /// <param name="filterContext">ASP.NET Core のActionFilterの仕組み</param>
                    /// <param name="metadata">Actionに関するメタ情報</param>
                    public virtual void {{ON_AUTOGENERATED_ACTION_EXECUTED}}(ActionExecutedContext filterContext, {{AUTOGENERATED_ACTION_METADATA}} metadata) {
                        // 自動生成されたエンドポイント全般に適用される処理がある場合はこのメソッドをオーバーライドして定義してください。
                    }
                    """)
                .AddWebapiMethod($$"""
                    /// <summary>
                    /// 自動生成されたASP.NET Core の Action の認証処理。
                    /// </summary>
                    /// <param name="filterContext">ASP.NET Core のActionFilterの仕組み</param>
                    /// <param name="metadata">Actionに関するメタ情報</param>
                    public virtual void {{ON_AUTOGENERATED_ACTION_AUTHORIZATION}}(AuthorizationFilterContext filterContext, {{AUTOGENERATED_ACTION_METADATA}} metadata) {
                        // 自動生成されたエンドポイント全般に適用される認証処理がある場合はこのメソッドをオーバーライドして定義してください。
                    }
                    """);
        }
        #endregion ASP.NET Core のバインディング設定
    }
}
