using System;
using System.IO;
using System.Reflection;
using System.Text;
using Microsoft.Extensions.DependencyInjection;

namespace HalApplicationBuilder {
    public class Program {

        static void Main(string[] args) {
            var serviceCollection = new ServiceCollection();
            var assembly = Assembly.LoadFile("/__local__/20221211_haldoc_csharp/haldoc/HalApplicationBuilderSampleSchema/bin/Debug/net5.0/HalApplicationBuilderSampleSchema.dll");
            HalApp.Configure(serviceCollection, new Core.Config {
                DbContextName = "SampleDbContext",
                DbContextNamespace = "HalApplicationBuilderSampleMvc.EntityFramework",
                EntityNamespace = "HalApplicationBuilderSampleMvc.EntityFramework.Entities",
                MvcModelNamespace = "HalApplicationBuilderSampleMvc.Models",
                MvcControllerNamespace = "HalApplicationBuilderSampleMvc.Controllers",
                MvcViewDirectoryRelativePath = "Views/__AutoGenerated",
            }, assembly);

            serviceCollection
                .BuildServiceProvider()
                .GetRequiredService<HalApp>()
                .GenerateCode(Console.Out);
        }
    }
}
