using System;
using System.IO;
using System.Reflection;
using System.Text;

namespace HalApplicationBuilder {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine("コード自動生成開始");

            var config = new Core.Config {
                DbContextName = "SampleDbContext",
                DbContextNamespace = "HalApplicationBuilderSampleMvc.EntityFramework",
                EntityNamespace = "HalApplicationBuilderSampleMvc.EntityFramework.Entities",
                MvcModelNamespace = "HalApplicationBuilderSampleMvc.Models",
                MvcControllerNamespace = "HalApplicationBuilderSampleMvc.Controllers",
                MvcViewDirectoryRelativePath = "Views/__AutoGenerated",
            };
            var dll = Assembly.LoadFile("/__local__/20221211_haldoc_csharp/haldoc/HalApplicationBuilderSampleSchema/bin/Debug/net5.0/HalApplicationBuilderSampleSchema.dll");
            var builder = new Core.Builder(dll, config);

            Console.WriteLine("コード自動生成: Entity定義");
            var efSourceDir = "/__local__/20221211_haldoc_csharp/haldoc/HalApplicationBuilderSampleMvc/EntityFramework";
            var efSourceFile = Path.Combine(efSourceDir, "__AutoGeneratedEntities.cs");
            if (!Directory.Exists(efSourceDir)) Directory.CreateDirectory(efSourceDir);
            using (var sw = new StreamWriter(efSourceFile, append: false, encoding: Encoding.UTF8)) {
                var source = new EntityFramework.EFCoreSource { AggregateBuilder = builder, Config = config };
                sw.Write(source.TransformText());
            }

            Console.WriteLine("コード自動生成: MVC Model");
            var modelDir = "/__local__/20221211_haldoc_csharp/haldoc/HalApplicationBuilderSampleMvc/Models";
            var modelFile = Path.Combine(modelDir, "__AutoGeneratedModels.cs");
            if (!Directory.Exists(modelDir)) Directory.CreateDirectory(modelDir);
            using (var sw = new StreamWriter(modelFile, append: false, encoding: Encoding.UTF8)) {
                var source = new AspNetMvc.MvcModels { AggregateBuilder = builder, Config = config };
                sw.Write(source.TransformText());
            }

            Console.WriteLine("コード自動生成: MVC View - 既存ファイル削除");
            var viewDir = Path.Combine("/__local__/20221211_haldoc_csharp/haldoc/HalApplicationBuilderSampleMvc", config.MvcViewDirectoryRelativePath);
            if (!Directory.Exists(viewDir)) Directory.CreateDirectory(viewDir);
            foreach (var file in Directory.GetFiles(viewDir)) {
                File.Delete(file);
            }

            Console.WriteLine("コード自動生成: MVC View - MultiView");
            foreach (var aggregate in builder.EnumerateRootAggregates()) {
                var view = new AspNetMvc.MultiView { RootAggregate = aggregate };
                var filename = Path.Combine(viewDir, view.FileName);
                using var sw = new StreamWriter(filename, append: false, encoding: Encoding.UTF8);
                sw.Write(view.TransformText());
            }

            Console.WriteLine("コード自動生成: MVC View - SingleView");
            foreach (var aggregate in builder.EnumerateRootAggregates()) {
                var view = new AspNetMvc.SingleView { RootAggregate = aggregate };
                var filename = Path.Combine(viewDir, view.FileName);
                using var sw = new StreamWriter(filename, append: false, encoding: Encoding.UTF8);
                sw.Write(view.TransformText());
            }

            Console.WriteLine("コード自動生成: MVC View - CreateView");
            foreach (var aggregate in builder.EnumerateRootAggregates()) {
                var view = new AspNetMvc.CreateView { RootAggregate = aggregate };
                var filename = Path.Combine(viewDir, view.FileName);
                using var sw = new StreamWriter(filename, append: false, encoding: Encoding.UTF8);
                sw.Write(view.TransformText());
            }

            Console.WriteLine("コード自動生成: MVC Controller");
            var controllerDir = "/__local__/20221211_haldoc_csharp/haldoc/HalApplicationBuilderSampleMvc/Controllers";
            var controllerFile = Path.Combine(controllerDir, "__AutoGeneratedControllers.cs");
            if (!Directory.Exists(controllerDir)) Directory.CreateDirectory(controllerDir);
            using (var sw = new StreamWriter(controllerFile, append: false, encoding: Encoding.UTF8)) {
                var source = new AspNetMvc.Controller { AggregateBuilder = builder, Config = config };
                sw.Write(source.TransformText());
            }

            Console.WriteLine("コード自動生成終了");
        }
    }
}
