using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HalApplicationBuilder.IntegrationTest.Perspectives {
    partial class Perspective {
        [UseDataPatterns]
        public async Task コンパイルエラーチェック(DataPattern pattern) {
            try {
                File.WriteAllText(SharedResource.Project.GetAggregateSchemaPath(), pattern.LoadXmlString());
                SharedResource.Project.CodeGenerator.UpdateAutoGeneratedCode();
                using var ct = new CancellationTokenSource();
                await SharedResource.Project.Debugger.BuildAsync(ct.Token, noEmit: true);
            } catch {
                TestContext.Out.WriteLine("--- SCHEMA ---");
                TestContext.Out.WriteLine(SharedResource.Project.BuildSchema().Graph.ToMermaidText());
                throw;
            }
        }
    }
}
