import * as React from "react"
import * as Input from "../../input"
import * as Layout from "../../layout"
import { VForm3 } from "../../layout"
import { カテゴリマスタDisplayData } from "../../__autoGenerated/カテゴリマスタ"
import { useNavigate } from "react-router-dom"

export const カテゴリマスタ一覧検索画面 = () => {
  const navigate = useNavigate()

  /** 一覧表示のカラム定義 */
  const getColumnDefs: Layout.GetColumnDefsFunction<カテゴリマスタDisplayData> = React.useCallback(cellType => [
    cellType.text("values.カテゴリID", "カテゴリID"),
    cellType.text("values.カテゴリ名", "カテゴリ名"),
  ], [])

  return (
    <Layout.MultiView
      queryModel="カテゴリマスタ"
      isReady={true}
      title="カテゴリマスタ一覧検索"
      getColumnDefs={getColumnDefs}
      headerButtons={
        <button
          onClick={() => navigate('/カテゴリマスタ/new')}
          className="px-3 py-1 bg-green-500 text-white rounded hover:bg-green-600"
        >
          新規登録
        </button>
      }
    >
      {({ reactHookFormMethods: { control } }) => (
        <VForm3.Root labelWidth="8rem">
          <VForm3.BreakPoint>
            <VForm3.Item label="カテゴリID">
              <Input.Word name="filter.カテゴリID" control={control} />
            </VForm3.Item>
            <VForm3.Item label="カテゴリ名">
              <Input.Word name="filter.カテゴリ名" control={control} />
            </VForm3.Item>
          </VForm3.BreakPoint>
        </VForm3.Root>
      )}
    </Layout.MultiView>
  )
}
