import * as React from "react"
import * as ReactHookForm from "react-hook-form"
import * as Layout from "../layout"
import * as Input from "../input"
import { MetadataForPage } from "../__autoGenerated/util/metadata-for-page"
import { getValueByPath } from "../layout/EditableGrid/EditableGrid.utils"
import { MetadataSchema } from "./getSchema"
import { ReflectionFormContext } from "./Parts.FormContext"

export const ReflectionGridInSingleView = ({ ownerPhysicalName, owner, ancestorsPath, className }: {
  ancestorsPath: string
  ownerPhysicalName: string
  owner: MetadataForPage.StructureMetadata
  className?: string
}) => {
  const { schema, formMethods: { control } } = React.useContext(ReflectionFormContext)

  const arrayPath = ancestorsPath ? `${ancestorsPath}.${ownerPhysicalName}` : ownerPhysicalName
  const { fields, append, remove } = ReactHookForm.useFieldArray({ control, name: arrayPath })
  const getColumnDefs = useReflectionGridColumnDefs(owner, schema)

  return (
    <Layout.EditableGrid
      getColumnDefs={getColumnDefs}
      rows={fields}
      className={className}
    />
  )
}

/**
 * 構造体のメタデータを受け取って EditableGrid を構築して返すコンポーネント
 */
export const useReflectionGridColumnDefs = (
  /** 構造体のメタデータ */
  metadata: MetadataForPage.StructureMetadata,
  /** メタデータのスキーマ */
  schema: MetadataSchema,
) => {
  const getColumnDefs: Layout.GetColumnDefsFunction<ReactHookForm.FieldValues> = React.useCallback(cellType => {
    const columns = collectGridColumns(metadata)
    return columns.map(({ memberPhysicalName, memberMetadata }) => toGridColumnDef(memberPhysicalName, memberMetadata, cellType))
  }, [metadata])

  return getColumnDefs
}

/**
 * 自身のメンバーと、子孫のうちChildAggregateのメンバーを集める。
 * ChildrenAggregateは除外
 */
const collectGridColumns = (metadata: MetadataForPage.StructureMetadata): { memberPhysicalName: string, memberMetadata: MetadataForPage.StructureMetadataMember }[] => {
  const result: { memberPhysicalName: string, memberMetadata: MetadataForPage.StructureMetadataMember }[] = []
  for (const [memberPhysicalName, memberMetadata] of Object.entries(metadata.members)) {
    if (memberMetadata.type === "ChildrenAggregate") {
      // ChildrenAggregateのメンバーはグリッドで表現できないので除外

    } else if (memberMetadata.type === "ChildAggregate") {
      result.push(...collectGridColumns(memberMetadata))

    } else {
      result.push({ memberPhysicalName, memberMetadata })
    }
  }
  return result
}

/**
 * メンバーのメタデータを受け取って GridColumnDef を構築して返す
 */
const toGridColumnDef = <
  TRow extends ReactHookForm.FieldValues
>(
  memberPhysicalName: string,
  member: MetadataForPage.StructureMetadataMember,
  cellType: Layout.ColumnDefFactories<TRow>
): Layout.EditableGridColumnDef<TRow> => {

  const fieldPath = `values.${memberPhysicalName}`

  if (member.type === "word" || member.type === "description") {
    return cellType.text(fieldPath as ReactHookForm.FieldPathByValue<TRow, string | undefined>, member.displayName)
  }

  if (member.type === "int" || member.type === "decimal" || member.type === "year" || member.type === "yearmonth") {
    return cellType.number(fieldPath as ReactHookForm.FieldPathByValue<TRow, number | undefined>, member.displayName)
  }

  if (member.type === "date" || member.type === "datetime") {
    return cellType.date(fieldPath as ReactHookForm.FieldPathByValue<TRow, string | undefined>, member.displayName)
  }

  if (member.type === "bool") {
    return cellType.boolean(fieldPath as ReactHookForm.FieldPathByValue<TRow, boolean>, member.displayName)
  }

  return cellType.other(member.displayName)
}

/** 外部参照の列定義を作成する。 */
const toGridColumnDefForRefTo = <
  TRow extends ReactHookForm.FieldValues
>(
  memberPhysicalName: string,
  member: MetadataForPage.RefMetadata,
  cellType: Layout.ColumnDefFactories<TRow>
) => {
  return cellType.other(member.displayName, {
    renderCell: (row) => {
      const refToObject = getValueByPath(row, `values.${memberPhysicalName}`)
      return (
        <div>
          TODO
        </div>
      )
    }
  })
}
