import * as React from "react"
import * as ReactHookForm from "react-hook-form"
import * as Layout from "../layout"
import * as Input from "../input"
import { MetadataForPage } from "../__autoGenerated/util"
import { MetadataSchema } from "./getSchema"
import { ReflectionForm } from "./Parts.Form"

/** QueryModel1件の詳細を閲覧・編集する画面 */
export const SingleView = ({ rootAggregatePhysicalName, metadata, schema }: {
  rootAggregatePhysicalName: string
  metadata: MetadataForPage.StructureMetadata
  schema: MetadataSchema
}) => {

  // フォーム
  const form = ReactHookForm.useForm()

  return (
    <Layout.PageFrame
      headerContent={(
        <Layout.PageFrameTitle>
          {metadata.displayName}
        </Layout.PageFrameTitle>
      )}
      className="p-4"
    >
      <ReflectionForm
        mode="single-view"
        metadataPhysicalName={rootAggregatePhysicalName}
        metadata={metadata}
        schema={schema}
        formMethods={form}
      />
    </Layout.PageFrame>
  )
}
