
namespace haldoc {
    using Microsoft.EntityFrameworkCore;

    partial class DynamicDbContext {
    
        public DbSet<haldoc.AutoGenerated.Entities.取引先> 取引先 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.請求情報> 請求情報 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.取引先支店> 取引先支店 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.営業所> 営業所 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.担当者> 担当者 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.上場企業資本情報> 上場企業資本情報 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.非上場企業資本情報> 非上場企業資本情報 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.コメント> コメント { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.連絡先> 連絡先 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.取引先>()
                .HasKey(e => new {
                    e.企業ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.請求情報>()
                .HasKey(e => new {
                    e.取引先__企業ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.取引先支店>()
                .HasKey(e => new {
                    e.会社__企業ID,
                    e.支店連番,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.営業所>()
                .HasKey(e => new {
                    e.営業所ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.担当者>()
                .HasKey(e => new {
                    e.ユーザーID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.上場企業資本情報>()
                .HasKey(e => new {
                    e.企業ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.非上場企業資本情報>()
                .HasKey(e => new {
                    e.企業ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.コメント>()
                .HasKey(e => new {
                    e.企業ID,
                    e.Index,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.連絡先>()
                .HasKey(e => new {
                });
        }
    }
}

namespace haldoc.AutoGenerated.Entities {

    public partial class 取引先 {
        public string 企業ID { get; set; }
        public string 企業名 { get; set; }
        public haldoc.E_重要度? 重要度 { get; set; }
        public int? 資本情報 { get; set; }
    }
    public partial class 請求情報 {
        public string 取引先__企業ID { get; set; }
        public string 宛名 { get; set; }
    }
    public partial class 取引先支店 {
        public string 会社__企業ID { get; set; }
        public string 支店連番 { get; set; }
        public string 支店名 { get; set; }
    }
    public partial class 営業所 {
        public string 営業所ID { get; set; }
        public string 営業所名 { get; set; }
    }
    public partial class 担当者 {
        public string ユーザーID { get; set; }
        public string 氏名 { get; set; }
        public string 所属__営業所ID { get; set; }
    }
    public partial class 上場企業資本情報 {
        public decimal 自己資本比率 { get; set; }
        public decimal 利益率 { get; set; }
    }
    public partial class 非上場企業資本情報 {
        public string 主要株主 { get; set; }
        public haldoc.E_安定性 安定性 { get; set; }
    }
    public partial class コメント {
        public string Text { get; set; }
        public string At { get; set; }
        public string By__ユーザーID { get; set; }
    }
    public partial class 連絡先 {
        public string 郵便番号 { get; set; }
        public string 都道府県 { get; set; }
        public string 市町村 { get; set; }
        public string 丁番地 { get; set; }
    }

}