
namespace haldoc {
    using Microsoft.EntityFrameworkCore;

    partial class DynamicDbContext {
    
        public DbSet<haldoc.AutoGenerated.Entities.取引先> 取引先 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.請求情報> 請求情報 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.取引先支店> 取引先支店 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.営業所> 営業所 { get; set; }
        public DbSet<haldoc.AutoGenerated.Entities.担当者> 担当者 { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder) {
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.取引先>()
                .HasKey(e => new {
                    e.企業ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.請求情報>()
                .HasKey(e => new {
                    e.取引先__企業ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.取引先支店>()
                .HasKey(e => new {
                    e.会社__企業ID,
                    e.支店ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.営業所>()
                .HasKey(e => new {
                    e.営業所ID,
                });
            modelBuilder.Entity<haldoc.AutoGenerated.Entities.担当者>()
                .HasKey(e => new {
                    e.ユーザーID,
                });
        }
    }
}

namespace haldoc.AutoGenerated.Entities {

    public partial class 取引先 {
        public string 企業ID { get; set; }
        public string 企業名 { get; set; }
        public haldoc.E_重要度? 重要度 { get; set; }
    }
    public partial class 請求情報 {
        public string 取引先__企業ID { get; set; }
        public string 宛名 { get; set; }
        public string 住所__郵便番号 { get; set; }
        public string 住所__都道府県 { get; set; }
        public string 住所__市町村 { get; set; }
        public string 住所__丁番地 { get; set; }
    }
    public partial class 取引先支店 {
        public string 会社__企業ID { get; set; }
        public string 支店ID { get; set; }
        public string 支店名 { get; set; }
    }
    public partial class 営業所 {
        public string 営業所ID { get; set; }
        public string 営業所名 { get; set; }
    }
    public partial class 担当者 {
        public string ユーザーID { get; set; }
        public string 氏名 { get; set; }
        public string 所属__営業所ID { get; set; }
    }

}