import React from "react"
import useEvent from "react-use-event-hook"
import { useForm } from "react-hook-form"
import { Button } from "../ui/Button"
import { WordTextBox } from "../ui/WordTextBox"
import { maxLengthOf } from "../app/fieldMetadata"
import { FormLabel } from "../ui/FormLabel"
import { PageTitle } from "../ui/PageTitle"
import { ログインParameterDisplayData } from "../__autoGenerated/ログインParameter"
import デバッグメニュー from "../debug-rooms/デバッグメニュー"
import * as DetailMessage from "../app/DetailMessageContext"
import { useLoginLogout } from "../app/useLoginLogout"
import { NowLoading } from "../ui/NowLoading"

/**
 * ログイン画面。
 * ログインしていない状態の場合はこのコンポーネント自身が定義するUIを表示。
 * ログインしている状態の場合は、props.childrenで指定されたアプリケーション本体の画面を表示する。
 *
 * ログイン状態は sessionStorage を使ってブラウザの複数タブ間で共有する。
 */
export function P001_ログイン(props: {
  /**
   * ログイン後画面。
   * ログインしていない状態では表示されない。
   */
  children: React.ReactNode
}) {

  const { loginUser, loginAsync, initializing } = useLoginLogout()
  const { setFocus, handleSubmit, control, register } = useForm<ログインParameterDisplayData>({
    defaultValues: {
      従業員番号: "admin",
      パスワード: "password123",
    },
  })

  // 初期表示時、またはログアウト後
  React.useEffect(() => {
    if (!initializing && !loginUser) {
      setFocus("従業員番号")
    }
  }, [initializing, loginUser])

  const [processing, setProcessing] = React.useState(false)
  const onSubmit = useEvent(async (data: ログインParameterDisplayData) => {
    if (processing) return
    setProcessing(true)
    await loginAsync(data)
    setProcessing(false)
  })

  // 初期化中の場合は何も表示しない
  if (initializing) return null

  // ログインしていない場合はログイン画面を表示
  if (!loginUser) return (
    <div className="min-h-screen flex items-center justify-center bg-gray-100">
      <div className="relative bg-white p-8 rounded shadow-md w-full max-w-md">
        <div className="mb-6">
          <PageTitle>ログイン</PageTitle>
          <DetailMessage.Rest />
        </div>
        <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col items-stretch gap-4 items-center">

          <div className="flex gap-4">
            <FormLabel className="basis-24 shrink-0">従業員番号</FormLabel>
            <div className="flex-1">
              <WordTextBox {...register("従業員番号")} maxLength={maxLengthOf("ログインParameter", "従業員番号")} className="w-full" />
              <DetailMessage.Of name="従業員番号" control={control} />
            </div>
          </div>

          <div className="flex gap-4">
            <FormLabel className="basis-24 shrink-0">パスワード</FormLabel>
            <div className="flex-1">
              <WordTextBox {...register("パスワード")} type="password" maxLength={maxLengthOf("ログインParameter", "パスワード")} className="w-full" />
              <DetailMessage.Of name="パスワード" control={control} />
            </div>
          </div>

          <Button submit fill className="col-span-2 justify-center mt-4">ログイン</Button>
        </form>

        {processing && <NowLoading />}
      </div>

      {import.meta.env.DEV && (
        <div className="fixed top-0 left-0 m-2">
          <デバッグメニュー />
        </div>
      )}

    </div>
  )

  // ログインしている場合は、子コンポーネントを表示
  return <>{props.children}</>
}
