import React from "react"
import * as ReactHookForm from "react-hook-form"
import * as ReactRouter from "react-router-dom"
import { PageBase } from "../app/PageBase"
import { useRevalidator } from "react-router-dom"
import { 売上詳細DisplayData, createNew売上詳細の売上明細DisplayData, deepEqual売上詳細 } from "../__autoGenerated/売上詳細"
import { callComplexPostEndpointAsync } from "../example/callComplexPostEndpointAsync"
import useEvent from "react-use-event-hook"
import dayjs from "dayjs"
import { maxLengthOf, numericPropsOf } from "../app/fieldMetadata"
import { FormLabel } from "../ui/FormLabel"
import { WordTextBox } from "../ui/WordTextBox"
import { DateInput } from "../ui/DateInput"
import { DescriptionTextArea } from "../ui/DescriptionTextArea"
import * as Grid from "../ui/grid"
import { Button } from "../ui/Button"
import { AsyncComboBox } from "../ui/AsyncComboBox"
import { createNew商品SearchCondition, 商品RefTarget } from "../__autoGenerated/商品"
import { UUID } from "uuidjs"
import * as DetailMessage from "../app/DetailMessageContext"
import { createNew売上詳細画面初期表示ParameterDisplayData } from "../__autoGenerated/売上詳細画面初期表示Parameter"
import { toWillBeChangedApplied } from "../example/toWillBeChangedApplied"

/**
 * P101_売上詳細 へ遷移するためのリンクURLを取得する関数
 */
export function getLinkUrlToP101売上詳細(売上SEQ?: string | null) {
  if (売上SEQ) {
    return `/uriage/edit/${売上SEQ}`
  } else {
    return `/uriage/new`
  }
}

/**
 * ルーティング定義
 */
export default [
  {
    path: "/uriage/new",
    element: <P101_売上詳細 mode="new" />,
    loader: async () => {
      const parameter = createNew売上詳細画面初期表示ParameterDisplayData()
      parameter.新規登録モード = true
      const result = await callComplexPostEndpointAsync('売上詳細画面初期表示', parameter, {
        ignoreConfirm: true,
      })
      if (result.type !== 'ok') throw result
      return result.returnValue
    },
  },
  {
    path: "/uriage/edit/:id",
    element: <P101_売上詳細 mode="edit" />,
    loader: async ({ params }) => {
      const parameter = createNew売上詳細画面初期表示ParameterDisplayData()
      parameter.新規登録モード = false
      parameter.売上SEQ = params.id ?? ''

      const result = await callComplexPostEndpointAsync('売上詳細画面初期表示', parameter, {
        ignoreConfirm: true,
      })
      if (result.type !== 'ok') throw result
      return result.returnValue
    },
  },
] satisfies ReactRouter.RouteObject[]

/**
 * P101 売上詳細
 */
function P101_売上詳細(props: {
  mode: 'new' | 'edit'
}) {

  // react-hook-form のフォーム管理を利用
  const loaderData = ReactRouter.useLoaderData() as 売上詳細DisplayData
  const formMethods = ReactHookForm.useForm<売上詳細DisplayData>({
    defaultValues: loaderData,
  })
  const { register, control, getValues, setValue, reset } = formMethods
  const { revalidate } = useRevalidator()
  const navigate = ReactRouter.useNavigate()
  const [saving, setSaving] = React.useState(false)

  const maxLen商品コード = maxLengthOf("売上詳細", "売上詳細の売上明細.0.商品.外部システム側ID")
  const numProps数量 = numericPropsOf("売上詳細", "売上詳細の売上明細.0.売上数量")
  const numProps手修正 = numericPropsOf("売上詳細", "売上詳細の売上明細.0.売上総額_税込_手修正")

  // 列定義（下の useFieldArrayForEditableGrid2 呼び出しの中）から remove を呼べるようにするための ref。
  // 同一文の中で自分自身の戻り値（remove）を参照すると型推論が循環してしまうため、
  // 呼び出しより前に宣言した ref 経由で間接的に参照する。
  const removeRef = React.useRef<(index: number) => void>(() => { })

  const {
    fieldArrayReturn: { append, remove },
    editableGrid2Props,
  } = Grid.useFieldArrayForEditableGrid2(
    { name: "売上詳細の売上明細", control, getValues, setValue },
    helper => [
      helper.enumeration("区分", "区分", "売上明細区分", { defaultWidth: 80 }),
      helper.text("商品コード", "商品.外部システム側ID", { defaultWidth: 140, maxLength: maxLen商品コード }),
      helper.text("商品名", "商品.商品名", { defaultWidth: 256, isReadOnly: true }),
      helper.numeric("単価(税抜)", "商品.売値単価_税抜", { defaultWidth: 120, isReadOnly: true, suffix: "円", commaSeparated: true }),
      helper.numeric("数量", "売上数量", { defaultWidth: 100, ...numProps数量 }),
      helper.text("消費税区分", "商品.消費税区分", { defaultWidth: 110, isReadOnly: true }),
      helper.numeric("金額(税込)", "売上総額_税込_自動計算", {
        defaultWidth: 140,
        isReadOnly: true,
        suffix: "円",
        commaSeparated: true,
        // 手修正が入っている場合は打ち消し線で表示
        getCellClassName: row => row.売上総額_税込_手修正 ? "line-through opacity-30" : "",
      }),
      helper.numeric("手修正", "売上総額_税込_手修正", { defaultWidth: 140, ...numProps手修正 }),
      helper.button(() => "削除", (_row, rowIndex) => removeRef.current(rowIndex), {
        defaultWidth: 64,
        disableResizing: true,
        hidden: row => !!row.existsInDatabase,
      }),
      helper.detailMessage({ defaultWidth: 280 }),
    ],
    [maxLen商品コード, numProps数量, numProps手修正],
  )
  removeRef.current = remove

  // 画面タイトル
  const [browserTitle, pageTitle] = React.useMemo(() => {
    if (props.mode === 'new') {
      return ["売上登録", "売上登録"]
    } else {
      const date = dayjs(loaderData.売上日時).format('YYYY-MM-DD')
      return [
        `売上 No.${loaderData.売上SEQ} (${date})`,
        `売上 No.${loaderData.売上SEQ}`
      ]
    }
  }, [props.mode, loaderData])

  // 自動計算金額（計算処理の実体はサーバー側）
  const totalAmount = ReactHookForm.useWatch({ name: '合計金額', control })
  const abortControllerRef = React.useRef<AbortController | null>(null)
  const triggerRecalculation = React.useCallback(async () => {
    // 計算処理の重複実行対策
    abortControllerRef.current?.abort()
    abortControllerRef.current = new AbortController()

    const result = await callComplexPostEndpointAsync('売上金額シミュレート', getValues(), {
      ignoreConfirm: true,
      signal: abortControllerRef.current.signal,
    })
    if (result.type !== 'ok') return;
    if (abortControllerRef.current?.signal.aborted) return;

    setValue('合計金額', result.returnValue.合計金額)

    const currentArray = getValues().売上詳細の売上明細
    for (const detail of result.returnValue.売上詳細の売上明細) {
      const index = currentArray.findIndex(d => d.明細ID === detail.明細ID)
      if (index === -1) continue;
      setValue(`売上詳細の売上明細.${index}.売上総額_税込_自動計算`, detail.売上総額_税込_自動計算)
    }
  }, [getValues, setValue])

  // 自動計算のトリガーとなる項目が何かしら変更されたら再計算を実行
  const watchedFields = ReactHookForm.useWatch({ name: "売上詳細の売上明細", control })
  const recalculateTrigger = JSON.stringify((watchedFields ?? []).flatMap(field => [
    field.明細ID,
    field.区分,
    field.商品.外部システム側ID,
    field.売上数量,
    field.売上総額_税込_手修正,
  ]))
  React.useEffect(() => {
    triggerRecalculation()
  }, [recalculateTrigger, triggerRecalculation])

  // 明細行追加処理
  const handleCreateNewItem = useEvent((newItem: 商品RefTarget) => {
    const newDetail = createNew売上詳細の売上明細DisplayData()
    newDetail.明細ID = UUID.generate()
    newDetail.商品 = newItem
    newDetail.区分 = '売上'
    newDetail.売上数量 = '1'
    append(newDetail, { shouldFocus: false })
  })

  // 保存時処理
  const { replaceMessages, clearMessages } = DetailMessage.useSetter()
  const handleSave = useEvent(async () => {
    try {
      clearMessages()
      setSaving(true)

      const currentValues = toWillBeChangedApplied(loaderData, formMethods.getValues(), deepEqual売上詳細)

      if (props.mode === 'new') {
        const result = await callComplexPostEndpointAsync('売上新規登録', currentValues)
        if (result.type === 'ok') {
          replaceMessages(result.detail)

          // 保存されたデータでリセットして isDirty を false にする。
          // reset による State 更新が反映され、ブロックが解除されるのを待ってから遷移する
          reset(result.returnValue)
          const waitAndNavigate = () => {
            if (formMethods.formState.isDirty) {
              window.setTimeout(waitAndNavigate, 10)
            } else {
              navigate(getLinkUrlToP101売上詳細(result.returnValue.売上SEQ))
            }
          }
          waitAndNavigate()

        } else if (result.type === 'canceled') {
          // 何もしない
        } else if (result.type === 'error') {
          replaceMessages(result.detail)
        }

      } else {
        const result = await callComplexPostEndpointAsync('売上修正', currentValues)
        if (result.type === 'ok') {
          replaceMessages(result.detail)
          revalidate()
        } else if (result.type === 'canceled') {
          // 何もしない
        } else if (result.type === 'error') {
          replaceMessages(result.detail)
        }
      }
    } finally {
      setSaving(false)
    }
  })

  // 保存後に loaderData のインスタンスが更新されるのでフォーム内容をリセットする
  React.useEffect(() => {
    reset(loaderData)
  }, [loaderData, reset])

  return (
    <PageBase
      browserTitle={browserTitle}
      isDirty={formMethods.formState.isDirty}
      className="gap-2 px-8 py-2"
      contents={(
        <div className="h-full max-w-6xl flex flex-col gap-y-2 overflow-hidden">

            {/* ヘッダ */}
            <div className="flex items-start gap-1">
              <div className="flex-1 flex flex-wrap items-center gap-1 py-1">
                <h1 className="text-lg font-bold">
                  {pageTitle}
                </h1>

                <div className="flex gap-2 items-center">
                  <FormLabel className="basis-20 shrink-0 text-right">売上日時</FormLabel>
                  <DateInput appearance="datetime" {...register("売上日時")} />
                </div>

                <div className="flex gap-2 items-center">
                  <FormLabel className="basis-20 shrink-0 text-right">担当者</FormLabel>
                  <div className="flex gap-2">
                    <WordTextBox {...register("担当者.従業員番号")} className="w-32" />
                    {getValues("担当者.氏名")}
                  </div>
                </div>
              </div>

              <Button fill onClick={handleSave} loading={saving}>
                保存
              </Button>
            </div>

            <DescriptionTextArea
              {...register("備考")}
              placeholder="備考"
              className="min-h-16 max-h-28"
            />

            <div className="flex justify-end font-bold">
              合計: {totalAmount}円
            </div>

            {/* 明細欄。行単位のメッセージはグリッドの各行のメッセージ列に表示されるが、
                明細欄全体（配列自体）に対するメッセージはここに表示する。 */}
            <DetailMessage.Of name="売上詳細の売上明細" control={control} />
            <Grid.EG2.EditableGrid2
              {...editableGrid2Props}
              isReadOnly={row => !!row.existsInDatabase}
              getRowClassName={row => row.区分 === '取消' ? 'text-rose-700' : ''}
              className="flex-1 min-h-32 border border-gray-300"
            />

            {/* 新規明細行追加欄 */}
            <NewItemArea formMethods={formMethods} onCreate={handleCreateNewItem} />
          </div>
      )}
    />
  )
}

/**
 * 新規明細行追加エリア。
 * 商品と数量だけを選択する。金額調整などは追加後に行う。
 */
function NewItemArea(props: {
  formMethods: ReactHookForm.UseFormReturn<売上詳細DisplayData>
  onCreate: (newItem: 商品RefTarget) => void
}) {
  const [searchCode, setSearchCode] = React.useState('')
  const [searchName, setSearchName] = React.useState('')
  const [errorMessage, setErrorMessage] = React.useState<string | null>(null)
  const [searching, setSearching] = React.useState(false)

  const handleSearchCode = async () => {
    if (!searchCode) return
    setSearching(true)
    setErrorMessage(null)
    try {
      const searchCondition = createNew商品SearchCondition()
      searchCondition.filter.外部システム側ID = searchCode
      searchCondition.take = '2' // ありえないが複数ヒットを考慮

      const result = await callComplexPostEndpointAsync('ref-to:商品', searchCondition, {
        ignoreConfirm: true,
      })
      if (result.type === 'ok') {
        if (result.returnValue.totalCount === 0) {
          setErrorMessage('該当する商品がありません')
        } else if (result.returnValue.totalCount === 1) {
          props.onCreate(result.returnValue.currentPageItems[0])
          setSearchCode('')
        } else {
          setErrorMessage('複数の商品がヒットしました。コードを確認してください。')
        }
      } else {
        setErrorMessage('検索エラーが発生しました')
      }
    } catch (e) {
      setErrorMessage('検索中にエラーが発生しました')
      console.error(e)
    } finally {
      setSearching(false)
    }
  }

  const handleSearchName = React.useCallback(async (keyword: string) => {
    const searchCondition = createNew商品SearchCondition()
    searchCondition.filter.商品名 = keyword

    const result = await callComplexPostEndpointAsync('ref-to:商品', searchCondition, {
      ignoreConfirm: true,
    })
    if (result.type === 'ok') {
      return result.returnValue.currentPageItems
    }
    return []
  }, [])

  return (
    <div className="border border-gray-300 p-2 bg-gray-50 flex flex-col gap-2">

      <div className="flex gap-x-8 gap-y-2 flex-col md:flex-row">

        <h2 className="self-start font-bold text-sm text-gray-600">
          新規明細行追加
        </h2>
        <div className="basis-2"></div>

        <div className="flex flex-col">
          <label className="text-xs text-gray-500">商品コード</label>
          <div className="flex gap-1">
            <WordTextBox
              value={searchCode}
              onChange={(e) => setSearchCode(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault()
                  handleSearchCode()
                }
              }}
              placeholder="商品コードで検索"
              className="w-32"
            />
            <Button outline onClick={handleSearchCode} loading={searching} disabled={!searchCode}>
              検索
            </Button>
          </div>
        </div>

        <div className="flex flex-col">
          <label className="text-xs text-gray-500">商品名</label>
          <AsyncComboBox
            value={searchName}
            onChange={(e) => setSearchName(e.target.value)}
            onSearch={handleSearchName}
            onSelectItem={(item) => {
              props.onCreate(item)
              setSearchName('')
            }}
            renderItem={(item) => (
              <div>
                <div className="text-sm font-bold">{item.商品名}</div>
                <div className="text-xs text-gray-500">{item.外部システム側ID}</div>
              </div>
            )}
            itemKey={(item) => item.商品SEQ ?? ''}
            className="w-64"
            placeholder="商品名で検索"
          />
        </div>

      </div>
      {errorMessage && (
        <div className="text-red-600 text-sm">{errorMessage}</div>
      )}
    </div>
  )
}
