import React from "react"
import * as ReactRouter from "react-router-dom"
import { useNavigate, Link } from "react-router-dom"
import { SearchPageBase, SortComboItem } from "../app/SearchPageBase"
import { FormLabel } from "../ui/FormLabel"
import { WordTextBox } from "../ui/WordTextBox"
import { NumericTextBox } from "../ui/NumericTextBox"
import { EnumSearchCondition } from "../app/EnumSearchCondition"
import { DataTableColumn, NumericCell } from "../ui/DataTable"
import { numericPropsOf, maxLengthOf } from "../app/fieldMetadata"
import { 商品一覧SearchCondition, createNew商品一覧SearchCondition, 商品一覧DisplayData } from "../__autoGenerated/商品一覧"
import { createNew商品RefTarget, 商品RefTarget } from "../__autoGenerated/商品"
import { Controller, UseFormReturn } from "react-hook-form"
import { StockAdjustmentDialog } from "./shared/StockAdjustmentDialog"
import { UUID } from "uuidjs"
import { Button } from "../ui/Button"

export const URL = "/shohin"

/**
 * P300_商品 へ遷移するためのフック
 */
export function useNavigateToP300商品() {
  const navigate = useNavigate()
  return React.useCallback(() => {
    navigate(URL)
  }, [navigate])
}

/**
 * ルーティング定義
 */
export default {
  path: URL,
  element: <P300_商品 />,
  loader: undefined,
} satisfies ReactRouter.RouteObject

/**
 * P300 商品
 */
function P300_商品() {
  const [stockAdjDialogState, setStockAdjDialogState] = React.useState<{
    isOpen: boolean
    key: string | undefined
    product: 商品RefTarget | undefined
  }>({ isOpen: false, key: undefined, product: undefined })

  const sortOptions = React.useMemo((): SortComboItem<"商品一覧">[] => [
    { key: '商品一覧.商品SEQ', label: '商品SEQ' },
    { key: '商品一覧.外部システム側ID', label: '外部システム側ID' },
    { key: '商品一覧.商品名', label: '商品名' },
    { key: '商品一覧.売値単価_税抜', label: '売値単価(税抜)' },
    { key: '商品一覧.消費税区分', label: '消費税区分' },
    { key: '商品一覧.在庫数', label: '在庫数' },
  ], [])

  const createInitialCondition = React.useCallback((): 商品一覧SearchCondition => ({
    ...createNew商品一覧SearchCondition(),
    sort: ['商品一覧.商品SEQ（昇順）'],
  }), [])

  return (
    <>
      <SearchPageBase
        queryModelType="商品一覧"
        pageTitle="商品"
        searchConditionDefaultSize={160}
        sortOptions={sortOptions}
        createInitialCondition={createInitialCondition}
        renderSearchCondition={SearchCondition}
        defineSearchResultColumns={[() => [
          {
            header: '',
            widthPx: 60,
            render: row => (
              <Link
                className="text-sky-600 underline"
                to={`/shohin/${row.商品SEQ}`}>
                詳細
              </Link>
            ),
          },
          { header: '外部システム側ID', widthPx: 152, render: row => row.外部システム側ID },
          { header: '商品名', widthPx: 300, render: row => row.商品名 },
          { header: '売値単価(税抜)', widthPx: 140, render: row => <NumericCell value={row.売値単価_税抜} suffix="円" /> },
          { header: '消費税区分', widthPx: 120, render: row => row.消費税区分 },
          { header: '在庫数', render: row => <NumericCell value={row.在庫数} /> },
          {
            header: '',
            widthPx: 96,
            render: row => (
              <Button outline mini
                onClick={() => {
                  const refTarget = createNew商品RefTarget()
                  refTarget.商品SEQ = row.商品SEQ ?? undefined
                  refTarget.商品名 = row.商品名 ?? undefined
                  refTarget.外部システム側ID = row.外部システム側ID ?? undefined
                  setStockAdjDialogState({ isOpen: true, key: UUID.generate(), product: refTarget })
                }}
              >
                在庫調整
              </Button>
            ),
          },
        ] satisfies DataTableColumn<商品一覧DisplayData>[], []]}
      />
      {
        stockAdjDialogState.product && (
          <StockAdjustmentDialog
            key={stockAdjDialogState.key}
            isOpen={stockAdjDialogState.isOpen}
            onClose={() => setStockAdjDialogState(prev => ({ ...prev, isOpen: false }))}
            product={stockAdjDialogState.product}
          />
        )
      }
    </>
  )
}

function SearchCondition({ register, control, setFocus }: UseFormReturn<商品一覧SearchCondition>): React.ReactNode {

  React.useEffect(() => {
    setFocus("filter.外部システム側ID.from")
  }, [setFocus])

  return (
    <div className="h-full py-1 flex flex-col lg:flex-row lg:items-start gap-x-8 gap-y-2">

      {/* 左列 */}
      <div className="grid grid-cols-[10rem_24rem] gap-2">

        <FormLabel className="text-right">外部システム側ID</FormLabel>
        <Controller
          name="filter.外部システム側ID"
          control={control}
          render={({ field: { name, value, onChange, onBlur, ref } }) => (
            <div className="flex items-center gap-2" onBlur={onBlur}>
              <WordTextBox name={`${name}.from`} ref={ref}
                maxLength={maxLengthOf("商品一覧", "外部システム側ID")}
                value={value?.from ?? ""}
                onChange={e => onChange({ ...value, from: e.target.value })} />
              <span>～</span>
              <WordTextBox name={`${name}.to`}
                maxLength={maxLengthOf("商品一覧", "外部システム側ID")}
                value={value?.to ?? ""}
                onChange={e => onChange({ ...value, to: e.target.value })} />
            </div>
          )}
        />

        <FormLabel className="text-right">商品名</FormLabel>
        <WordTextBox {...register("filter.商品名")} maxLength={maxLengthOf("商品一覧", "商品名")} />
      </div>

      {/* 右列 */}
      <div className="grid grid-cols-[10rem_24rem] gap-2">

        <FormLabel className="text-right">売値単価(税抜)</FormLabel>
        <Controller
          name="filter.売値単価_税抜"
          control={control}
          render={({ field: { name, value, onChange, onBlur, ref } }) => (
            <div className="flex items-center gap-2" onBlur={onBlur}>
              <NumericTextBox name={`${name}.from`} ref={ref}
                {...numericPropsOf("商品一覧", "売値単価_税抜")}
                value={value?.from ?? ""}
                onChange={e => onChange({ ...value, from: e.target.value })} />
              <span>～</span>
              <NumericTextBox name={`${name}.to`}
                {...numericPropsOf("商品一覧", "売値単価_税抜")}
                value={value?.to ?? ""}
                onChange={e => onChange({ ...value, to: e.target.value })} />
            </div>
          )}
        />

        <FormLabel className="text-right">消費税区分</FormLabel>
        <EnumSearchCondition control={control} name="filter.消費税区分" type="消費税区分" />

        <FormLabel className="text-right">在庫数</FormLabel>
        <Controller
          name="filter.在庫数"
          control={control}
          render={({ field: { name, value, onChange, onBlur, ref } }) => (
            <div className="flex items-center gap-2" onBlur={onBlur}>
              <NumericTextBox name={`${name}.from`} ref={ref}
                {...numericPropsOf("商品一覧", "在庫数")}
                value={value?.from ?? ""}
                onChange={e => onChange({ ...value, from: e.target.value })} />
              <span>～</span>
              <NumericTextBox name={`${name}.to`}
                {...numericPropsOf("商品一覧", "在庫数")}
                value={value?.to ?? ""}
                onChange={e => onChange({ ...value, to: e.target.value })} />
            </div>
          )}
        />
      </div>
    </div>
  )
}
