using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MyApp.Core;

public partial class OverridedApplicationService : AutoGeneratedApplicationService {
    public OverridedApplicationService(IServiceProvider serviceProvider) : base(serviceProvider) {
    }

    /// <summary>
    /// 実行時設定。サーバーに配置された appsettings.json の値。
    /// </summary>
    public RuntimeSetting Settings => ServiceProvider.GetRequiredService<RuntimeSetting>();

    /// <summary>
    /// ユーザー1人が特定のCommand/Queryモデルに対して持っている権限レベルを返す
    /// </summary>
    public E_AuthLevel GetAuthLevel(E_CommandQueryType modelType) {
        return E_AuthLevel.Writable; // 特にロジックなし
    }
}

/// <summary>
/// ユーザー1人が特定のCommand/Queryモデルに対して持っている権限レベル
/// </summary>
public enum E_AuthLevel {
    /// <summary>権限なし</summary>
    None = 0,
    /// <summary>参照権限あり、更新権限なし</summary>
    Readable = 1,
    /// <summary>参照権限・更新権限ともにあり</summary>
    Writable = 2,
}
