using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;

namespace HalApplicationBuilder.Runtime {
    internal class FindService {
        internal FindService(RuntimeContext context) {
            RuntimeContext = context;
        }

        private RuntimeContext RuntimeContext { get; }

        internal TInstanceModel Find<TInstanceModel>(InstanceKey key) {
            // SQL発行回数が全く最適化されていないが後で考える
            var tables = new List<Core.AutoGenerateDbEntityClass>();
            tables.Add(key.Aggregate.ToDbTableModel());
            tables.AddRange(key.Aggregate
                .GetDescendants()
                .Select(aggregate => aggregate.ToDbTableModel()));

            var _ = new Core.ViewRenderingContext();
            var rootInstance = RuntimeContext
                .RuntimeAssembly
                .CreateInstance(key.Aggregate.ToInstanceModel(_).RuntimeFullName);

            throw new NotImplementedException();
        }
    }
}
