import * as React from "react"
import * as Input from "../../input"
import * as Layout from "../../layout"
import { VForm3 } from "../../layout"
import { 店舗マスタDisplayData, 店舗マスタSearchCondition } from "../../__autoGenerated/店舗マスタ"
import { 従業員マスタRefTarget } from "../../__autoGenerated/従業員マスタ"
import { useNavigate } from "react-router-dom"

export const 店舗マスタ一覧検索画面 = () => {
  const navigate = useNavigate()

  /** 一覧表示のカラム定義 */
  const getColumnDefs: Layout.GetColumnDefsFunction<店舗マスタDisplayData> = React.useCallback(cellType => [
    cellType.text("values.店舗ID", "店舗ID"),
    cellType.text("values.店舗名", "店舗名"),
    cellType.text("values.電話番号", "電話番号"),
    cellType.text("店舗マスタの住所.values.郵便番号", "郵便番号"),
    cellType.text("店舗マスタの住所.values.都道府県", "都道府県"),
    cellType.text("店舗マスタの住所.values.市区町村", "市区町村"),
    cellType.text("店舗マスタの住所.values.番地建物名", "番地・建物名"),
    cellType.text("営業時間.values.開店時間", "開店時間"),
    cellType.text("営業時間.values.閉店時間", "閉店時間"),
    cellType.text("values.店長.氏名", "店長"),
  ], [])

  return (
    <Layout.MultiView
      queryModel="店舗マスタ"
      isReady={true}
      title="店舗マスタ一覧検索"
      getColumnDefs={getColumnDefs}
      headerButtons={
        <button
          onClick={() => navigate('/店舗マスタ/new')}
          className="px-3 py-1 bg-green-500 text-white rounded hover:bg-green-600"
        >
          新規登録
        </button>
      }
    >
      {({ reactHookFormMethods: { control } }) => (
        <VForm3.Root labelWidth="8rem">
          <VForm3.BreakPoint>
            <VForm3.Item label="店舗ID">
              <Input.Word name="filter.店舗ID" control={control} />
            </VForm3.Item>
            <VForm3.Item label="店舗名">
              <Input.Word name="filter.店舗名" control={control} />
            </VForm3.Item>
            <VForm3.Item label="電話番号">
              <Input.Word name="filter.電話番号" control={control} />
            </VForm3.Item>
          </VForm3.BreakPoint>
          <VForm3.BreakPoint label="住所">
            <VForm3.Item label="郵便番号">
              <Input.Word name="filter.店舗マスタの住所.郵便番号" control={control} />
            </VForm3.Item>
            <VForm3.Item label="都道府県">
              <Input.Word name="filter.店舗マスタの住所.都道府県" control={control} />
            </VForm3.Item>
            <VForm3.Item label="市区町村">
              <Input.Word name="filter.店舗マスタの住所.市区町村" control={control} />
            </VForm3.Item>
            <VForm3.Item label="番地建物名">
              <Input.Word name="filter.店舗マスタの住所.番地建物名" control={control} />
            </VForm3.Item>
          </VForm3.BreakPoint>
          <VForm3.BreakPoint label="営業時間">
            <VForm3.Item label="開店時間">
              <Input.Word name="filter.営業時間.開店時間" control={control} />
            </VForm3.Item>
            <VForm3.Item label="閉店時間">
              <Input.Word name="filter.営業時間.閉店時間" control={control} />
            </VForm3.Item>
          </VForm3.BreakPoint>
          <VForm3.BreakPoint label="店長">
            <VForm3.Item label="従業員ID">
              <Input.Word name="filter.店長.従業員ID" control={control} />
            </VForm3.Item>
            <VForm3.Item label="氏名">
              <Input.Word name="filter.店長.氏名" control={control} />
            </VForm3.Item>
          </VForm3.BreakPoint>
        </VForm3.Root>
      )}
    </Layout.MultiView>
  )
}
