CREATE VIEW V_カテゴリ別売上 AS
SELECT
    STRFTIME('%Y/%m', T1.ORDER_DATE) AS 売上分析_年月,
    T1."店舗_STORE_ID" AS 売上分析_店舗_店舗ID,
    T3."カテゴリ_CATEGORY_ID" AS カテゴリ_カテゴリID,
    T4.CATEGORY_NAME AS カテゴリ_カテゴリ名, -- カテゴリマスタから取得
    SUM(T2.SUBTOTAL) AS 売上金額,
    CAST(SUM(T2.SUBTOTAL) AS REAL) / NULLIF((
        SELECT SUM(OD_INNER.SUBTOTAL)
        FROM ORDER_DETAILS AS OD_INNER
        INNER JOIN 注文履歴 AS OH_INNER ON OD_INNER.Parent_ORDER_ID = OH_INNER.ORDER_ID
        WHERE STRFTIME('%Y/%m', OH_INNER.ORDER_DATE) = STRFTIME('%Y/%m', T1.ORDER_DATE)
          AND OH_INNER."店舗_STORE_ID" = T1."店舗_STORE_ID"
    ), 0) AS 売上構成比
FROM
    注文履歴 AS T1
    INNER JOIN ORDER_DETAILS AS T2 ON T1.ORDER_ID = T2.Parent_ORDER_ID
    INNER JOIN 商品マスタ AS T3 ON T2."商品_PRODUCT_ID" = T3.PRODUCT_ID
    LEFT JOIN カテゴリマスタ AS T4 ON T3."カテゴリ_CATEGORY_ID" = T4.CATEGORY_ID
GROUP BY
    STRFTIME('%Y/%m', T1.ORDER_DATE),
    T1."店舗_STORE_ID",
    T3."カテゴリ_CATEGORY_ID",
    T4.CATEGORY_NAME; 