CREATE VIEW V_売上分析 AS
SELECT
    STRFTIME('%Y/%m', T1.ORDER_DATE) AS 年月,
    T1."店舗_STORE_ID" AS 店舗_店舗ID,
    T3.STORE_NAME AS 店舗_店舗名,
    T3.PHONE AS 店舗_電話番号,
    SA.POSTAL_CODE AS 店舗_住所_郵便番号,
    SA.PREFECTURE AS 店舗_住所_都道府県,
    SA.CITY AS 店舗_住所_市区町村,
    SA.ADDRESS_LINE AS 店舗_住所_番地建物名,
    BH.OPENING_TIME AS 店舗_営業時間_開店時間,
    BH.CLOSING_TIME AS 店舗_営業時間_閉店時間,
    E.ID AS 店舗_店長_従業員ID,
    E.NAME AS 店舗_店長_氏名,
    E.NAME_KANA AS 店舗_店長_氏名カナ,
    E.TAISHOKU AS 店舗_店長_退職日,
    SUM(T2.SUBTOTAL) AS 売上合計,
    COUNT(DISTINCT T1."顧客_CUSTOMER_ID") AS 客数,
    CASE WHEN COUNT(DISTINCT T1."顧客_CUSTOMER_ID") = 0 THEN 0 ELSE SUM(T2.SUBTOTAL) * 1.0 / COUNT(DISTINCT T1."顧客_CUSTOMER_ID") END AS 客単価,
    1 AS Version
FROM
    注文履歴 AS T1
    INNER JOIN ORDER_DETAILS AS T2 ON T1.ORDER_ID = T2.Parent_ORDER_ID
    LEFT JOIN 店舗マスタ AS T3 ON T1."店舗_STORE_ID" = T3.STORE_ID
    LEFT JOIN STORE_ADDRESS AS SA ON T3.STORE_ID = SA.Parent_STORE_ID
    LEFT JOIN BUSINESS_HOURS AS BH ON T3.STORE_ID = BH.Parent_STORE_ID
    LEFT JOIN EMPLOYEE AS E ON T3."店長_ID" = E.ID
    LEFT JOIN SHOZOKU AS SZ ON E.ID = SZ.Parent_ID
    LEFT JOIN BUSHO AS B ON SZ."部署_BUSHO_CD" = B.BUSHO_CD
    LEFT JOIN AUTHORITY AS A ON E.ID = A.Parent_ID
GROUP BY
    STRFTIME('%Y/%m', T1.ORDER_DATE),
    T1."店舗_STORE_ID",
    T3.STORE_NAME,
    T3.PHONE,
    SA.POSTAL_CODE,
    SA.PREFECTURE,
    SA.CITY,
    SA.ADDRESS_LINE,
    BH.OPENING_TIME,
    BH.CLOSING_TIME,
    E.ID,
    E.NAME,
    E.NAME_KANA,
    E.TAISHOKU;
    -- T3.ADDRESS_POSTAL_CODE,
    -- T3.ADDRESS_PREFECTURE,
    -- T3.ADDRESS_CITY,
    -- T3.ADDRESS_LINE,
    -- T3.OPEN_TIME,
    -- T3.CLOSE_TIME,
    -- T4.EMPLOYEE_ID,
    -- T4.FULL_NAME,
    -- T4.FULL_NAME_KANA; 