CREATE VIEW V_診療収益分析 AS
SELECT
    CAST(STRFTIME('%Y%m', T1.ORDER_DATE) AS INTEGER) AS 年月,
    T1."診療科_STORE_ID" AS 診療科_診療科ID,
    T3.STORE_NAME AS 診療科_診療科名,
    T3.PHONE AS 診療科_電話番号,
    SA.POSTAL_CODE AS 診療科_住所_郵便番号,
    SA.PREFECTURE AS 診療科_住所_都道府県,
    SA.CITY AS 診療科_住所_市区町村,
    SA.ADDRESS_LINE AS 診療科_住所_番地建物名,
    BH.OPENING_TIME AS 診療科_診療時間_開始時間,
    BH.CLOSING_TIME AS 診療科_診療時間_終了時間,
    E.ID AS 診療科_科長_医療従事者ID,
    E.NAME AS 診療科_科長_氏名,
    E.NAME_KANA AS 診療科_科長_氏名カナ,
    E.TAISHOKU AS 診療科_科長_退職日,
    SUM(T2.SUBTOTAL) AS 診療収益合計,
    COUNT(DISTINCT T1."患者_CUSTOMER_ID") AS 患者数,
    CASE WHEN COUNT(DISTINCT T1."患者_CUSTOMER_ID") = 0 THEN 0 ELSE SUM(T2.SUBTOTAL) * 1.0 / COUNT(DISTINCT T1."患者_CUSTOMER_ID") END AS 患者単価,
    1 AS Version
FROM
    "診療履歴" AS T1
    INNER JOIN ORDER_DETAILS AS T2 ON T1.ORDER_ID = T2.Parent_ORDER_ID
    LEFT JOIN "診療科マスタ" AS T3 ON T1."診療科_STORE_ID" = T3.STORE_ID
    LEFT JOIN STORE_ADDRESS AS SA ON T3.STORE_ID = SA.Parent_STORE_ID
    LEFT JOIN BUSINESS_HOURS AS BH ON T3.STORE_ID = BH.Parent_STORE_ID
    LEFT JOIN EMPLOYEE AS E ON T3."科長_ID" = E.ID
    LEFT JOIN SHOZOKU AS SZ ON E.ID = SZ.Parent_ID
    LEFT JOIN BUSHO AS B ON SZ."診療科_BUSHO_CD" = B.BUSHO_CD
    LEFT JOIN AUTHORITY AS A ON E.ID = A.Parent_ID
GROUP BY
    CAST(STRFTIME('%Y%m', T1.ORDER_DATE) AS INTEGER),
    T1."診療科_STORE_ID",
    T3.STORE_NAME,
    T3.PHONE,
    SA.POSTAL_CODE,
    SA.PREFECTURE,
    SA.CITY,
    SA.ADDRESS_LINE,
    BH.OPENING_TIME,
    BH.CLOSING_TIME,
    E.ID,
    E.NAME,
    E.NAME_KANA,
    E.TAISHOKU;
    -- T3.ADDRESS_POSTAL_CODE,
    -- T3.ADDRESS_PREFECTURE,
    -- T3.ADDRESS_CITY,
    -- T3.ADDRESS_LINE,
    -- T3.OPEN_TIME,
    -- T3.CLOSE_TIME,
    -- T4.EMPLOYEE_ID,
    -- T4.FULL_NAME,
    -- T4.FULL_NAME_KANA; 