using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HalApplicationBuilder.IntegrationTest.Perspectives {
    public class _デバッグ用ビルド {
        [UseDataPatterns]
        public async Task デバッグ用ビルド(DataPattern pattern) {
            try {
                File.WriteAllText(SharedResource.Project.GetAggregateSchemaPath(), pattern.LoadXmlString());
                SharedResource.Project.CodeGenerator.UpdateAutoGeneratedCode();
                await Task.WhenAll(
                    Task.Run(SharedResource.Project.Migrator.DeleteAndRecreateDatabase),
                    SharedResource.Project.Debugger.BuildAsync());
            } catch {
                NUnit.Framework.TestContext.Out.WriteLine("--- SCHEMA ---");
                NUnit.Framework.TestContext.Out.WriteLine(SharedResource.Project.BuildSchema().Graph.ToMermaidText());
                throw;
            }
        }
    }
}
